### ISSUE TITLE
Can't seem to make QML work on OS X

### ISSUE THREAD

**Issue by LukasBombach** [RSATom/WebChimera#100]
Hello,

I am trying to use QML in the simplest way possible. Using my Chrome (or nw.js) I run this website:

```html
<!DOCTYPE html>
<html>
<body>
<object type="application/x-chimera-plugin" width="640" height="360">
    <param name="filename" value="http://archive.org/download/CrayonDragonAnAnimatedShortFilmByTonikoPantoja/Crayon%20Dragon%20-%20An%20animated%20short%20film%20by%20Toniko%20Pantoja.mp4" />
    <param name="qmlsrc" value="player.qml">
</object>
</body>
</html>
```
using the following QML file: https://gist.github.com/LukasBombach/b2596af21e9baa03d64f

(It is the [QML from the Wiki](https://github.com/RSATom/WebChimera/wiki/Getting-started-with-QML))

I tried various ways to link the QML (absolute paths, relative paths, …). The video shows and plays, but I cannot see any of the elements defined in the QML.

**Comment by jaruba** [comment]
Grats for making issue nr. 100! :))

About your QML, it doesn't work on Windows either.. try this:

	import QtQuick 2.1
	import QmlVlc 0.1
	 
	Rectangle {
		id: bg
		color: "transparent"
		anchors.fill: parent
	 
		VlcVideoSurface {
			id: videoOutput
			source: vlcPlayer
			anchors.fill: parent
		}
	 
		MouseArea {
			anchors.fill: parent;
			onClicked: vlcPlayer.togglePause();
		}
	
		Rectangle {
			id: ppBtn
			color: 'white'
			height: 30
			width: 30
			anchors.horizontalCenter: parent.horizontalCenter
			anchors.bottom: parent.bottom
			anchors.bottomMargin: 20
	
			MouseArea {
				anchors.fill: parent
				onClicked: vlcPlayer.togglePause()
			}
	
			Connections {
				target: vlcPlayer
				onMediaPlayerPlaying: ppBtn.color = 'green'
				onMediaPlayerPaused: ppBtn.color = 'red'
			}
		}
	}

:)

**Comment by LukasBombach** [comment]
@jaruba Thanks for your answer. I still am having no luck on OS X. I tried referencing as
````html
<param name="qmlsrc" value="player.qml">
````
where the qml was in the same directory. I also tried an absolute path using `file://`. Also using `./player.qml` as value doesn't work.

**Comment by jaruba** [comment]
In node-webkit, WebChimera Player uses this:

    var webchimeraFolder = "file:///"+ process.cwd() +"/player";

To get the "player" folder.

So you can try using:

    var myQmlScript = "file:///"+ process.cwd() +"/player.qml";

in JS, and then use that variable as the path in ```qmlsrc```. :)

**Comment by LukasBombach** [comment]
@jaruba The problem does not seem to be a wrong file path. I tried your method and I copypasted the path to the address bar and the qml source shows up. I did this in node-webkit *and* in Chrome. Both play the video but do not show anything else. Do I have to install anything except for the plugin? For instance QT? I did install QT using homebrew (`brew install qt`) but no luck either.

**Comment by jaruba** [comment]
Don't need to install anything, but it should be noted that it is not possible to load local files in chrome. This is for security reasons. So you will have to put those files up on a web server to load them in chorme.

But in node-webkit this should not be the problem, as it is allowed to load local files there.

**Comment by jaruba** [comment]
For example.. To load QML from a string instead of a file (which is possible locally even when not in node-webkit), you can put your QML code in a ```<textarea>```:

	<textarea id="qmlcode">
	import QtQuick 2.1
	import QmlVlc 0.1
	
	Rectangle {
		id: bg
		color: bgcolor
		VlcVideoSurface {
			id: videoOutput
			source: vlcPlayer
			anchors.fill: parent
			MouseArea {
				anchors.fill: parent;
				onClicked: vlcPlayer.togglePause();
			}
		}
	}
	
	</textarea>

Then load it with JavaScript:

    document.getElementById("webchimera").qml = document.getElementById("qmlcode").value;

*Remember to change "webchimera" to your plugin object's element id.*

**Comment by LukasBombach** [comment]
This https://gist.github.com/LukasBombach/3e65166aa9153bb57a8b

will show me a flash of black rectangle, which then disappears, but then I can hear the video playing on a blank white screen (with the textarea placed somewhere). Both in Chrome (41.0.2272.104 (64-bit)) and node-webkit 0.12.0 64bit. All on a Mac running the latest Yosemite.

**Comment by jaruba** [comment]
If you put your code in the QML block at http://editor.webchimera.org/basic and hit Run, does it react the same?

**Comment by LukasBombach** [comment]
No, i can see the video, but no QML interface. It is also to be noted in all player demos (demos using the player JS) I only get a black screen and no video at all.

**Comment by jaruba** [comment]
That is very strange.. I used WebChimera on a Mac and didn't have any of these issues.

I think @RSATom can help you more with this, as it seems to be a Plugin error, your code works fine for me in the Online Editor on Windows.

**Comment by jaruba** [comment]
Although, it may also be possible that the Player shows a black screen (which usually means a QML Error) because I updated WebChimera Player on the site to v1.08.

This new version uses QtQuick.Controls for a new feature, and QtQuick.Controls was added in WebChimera Plugin v0.2.5, which has been released on Windows, but not yet on Mac.

So this is possibly the reason the demos don't work, but the Online Editor should of worked great.

Also, if you don't insist on using QML for the UI, you should also know that WebChimera Plugin on Mac is natively windowless.. so you can build your entire UI in HTML, CSS and JavaScript if you want. (but this is not cross-platform as it only happens on Mac, not sure how it is on Linux yet)

**Comment by RSATom** [comment]
@LukasBombach, Could you please try open http://rsatom.github.io/WebChimera/demos/basic/basic_2.htm? 
If no, could you please try install Firefox and start it via terminal?

**Comment by LukasBombach** [comment]
@RSATom That seems to be working! I see a pause button and time controls sliding in on mouseover.

![screen shot 2015-03-30 at 10 28 00](https://cloud.githubusercontent.com/assets/2379652/6892830/a546e07c-d6c7-11e4-84b2-796beb1af119.png)

**Comment by RSATom** [comment]
but http://www.webchimera.org/demos/default_skin don't work, right?

**Comment by LukasBombach** [comment]
No, instead of the vide, I see a black screen:

![image](https://cloud.githubusercontent.com/assets/2379652/6892911/96083600-d6c8-11e4-88c7-eee5a43f2887.png)

**Comment by RSATom** [comment]
ok, then it's possible `WebChimera Player` has some compatibility issue with `WebChimera Plugin` v0.2.4 . Could you please run Firefox via console and open http://www.webchimera.org/demos/default_skin ?

**Comment by LukasBombach** [comment]
No console output on http://www.webchimera.org/demos/default_skin 
![screen shot 2015-03-30 at 10 54 17](https://cloud.githubusercontent.com/assets/2379652/6893214/572158a6-d6cb-11e4-948e-64870676e783.png)

Some console output on http://rsatom.github.io/WebChimera/demos/basic/basic_2.htm 
![screen shot 2015-03-30 at 10 55 05](https://cloud.githubusercontent.com/assets/2379652/6893218/6b45aa4e-d6cb-11e4-9cd0-fe32792b4cd9.png)

**Comment by RSATom** [comment]
it seems logging not working on Mac OS X. Sad. Ok, but finally you need get it working on NW.js, right?

**Comment by LukasBombach** [comment]
I must try doing whatever you did on http://rsatom.github.io/WebChimera/demos/basic/basic_2.htm in NW. Currently I only called it in Chrome/Firefox and that (that specific website) worked. But I'm at work right now. Mus try later :)

**Comment by jaruba** [comment]
About WebChimera Player v1.08 compatibility issues with WebChimera Plugin v0.2.4 Mac, I mentioned above:

"This new version uses QtQuick.Controls for a new feature, and QtQuick.Controls was added in WebChimera Plugin v0.2.5, which has been released on Windows, but not yet on Mac."

**Comment by RSATom** [comment]
@jaruba, thanks for note.
@LukasBombach, ok, then when you will test it on NW.js, check if you have 

    "main": "app://host/index.html",
 
in your `package.json`, It enables `app://`protocol and enable loading local .qml files.

**Comment by RSATom** [comment]
And one more note - you have to use x64 NW.js build on Mac OS X (but ia32 build on Windows)

**Comment by jaruba** [comment]
WebChimera Player v1.07 should work on Mac in Node-Webkit. You can download it from:
https://github.com/jaruba/WebChimeraPlayer/releases

But you might also need to make this change to ``/player/webchimera.js`` manually, as it's part of the last release and it includes a fix for some node-webkit issues: https://github.com/jaruba/WebChimeraPlayer/commit/236623524836d5d100aeaa6271f02a0ff0abf20e

**Comment by RSATom** [comment]
Another way is use test version of `WebChimera Player` with already embedded `QtQuick.Controls`: https://dl.dropboxusercontent.com/u/94817236/WebChimera_0.2.5.1_vlc_2.2.0.dmg

**Comment by RSATom** [comment]
It should work fine regardless it's test version.

**Comment by LukasBombach** [comment]
Ok, making progress. If I use your source-code from http://rsatom.github.io/WebChimera/demos/basic/basic_2.htm in node-webkit and reference the remote QML file (online, using http) from your server, **it does work**!
```html
<object id="plugin_inst_1" type="application/x-chimera-plugin" width="640" height="480">
    <param name="autoplay" value="true" />
    <param name="mrl" value="http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_stereo.avi" />
    <param name="qmlsrc" value="http://rsatom.github.io/WebChimera/demos/basic/basic_2.qml" />
</object>
```

Now I tried to use

    "main": "app://host/index.html"

and reference a local file by either doing this:
```html
<param name="qmlsrc" value="basic_2.qml" />
<!-- or -->
<param name="qmlsrc" value="app://host/labs/webchimera/basic_2.qml" />
```
The QML seems not to be loaded and the video stays a black rectangle.

**Comment by RSATom** [comment]
no, you shouldn't add `app://host/labs...` to `qmlsrc`, you should pass there relative path. Treat folder where `package.json` resides as root folder.

**Comment by LukasBombach** [comment]
Woohoo. That does work now. Thank you!! Also sorry for all the fuzz.

**Comment by LukasBombach** [comment]
Woohoo. That does work now. Thank you!! Also sorry for all the fuzz.

**Comment by RSATom** [comment]
Don't worry, such cases allow us understand what exactly is not clear in our approach.

**Comment by LukasBombach** [comment]
:)

The demos on http://www.webchimera.org/demos/ still do not seem to work on my machine though (OS X Yosemite, Chrome Version 41.0.2272.104 (64-bit) / Firefox 36.0.4

**Comment by LukasBombach** [comment]
All I get is black rectangles

**Comment by jaruba** [comment]
do the demos from the developer kit on the download page work in node-webkit?

**Comment by LukasBombach** [comment]
Oh sorry, forgot to test, will test tomorrow. Some more feedback on why I had such difficulties on my machine. I followed the instructions on [Getting started with QML](https://github.com/RSATom/WebChimera/wiki/Getting-started-with-QML). The code as proposed does not work out of the box.

First of all you need to include

```qml
import QtQuick 2.1
import QtQuick.Layouts 1.0
import QmlVlc 0.1
```

on top of the qml. Second of all, the button won't show unless it is given a width and height. A working QML would look like this: https://gist.github.com/LukasBombach/3b4cb58724ec722ee571

**Comment by jaruba** [comment]
I checked the code at [Getting started with QML](https://github.com/RSATom/WebChimera/wiki/Getting-started-with-QML).

What you said is mostly correct.. the needed code in the header was:

    import QtQuick 2.1
    import QmlVlc 0.1

as none of the examples use ``QtQuick.Layouts``.

I edited the code on that page and also added an optimized version of the code you posted. (as it didn't really need 2 MouseArea's)

The thing with the MouseArea component is that it has it's own layering process above all the other components. Which means that it doesn't matter where the first one was called, if there is only one MouseArea it will always be on top of all other types of components (and in that code it was the width/height of the video surface, so practically almost the full size of the plugin object), only a second MouseArea can be above the first one.

I hope I explained it correctly, I realize I also posted the code with 2 MouseArea's in this post a while ago, should of been a bit more careful before posting. :)

**Comment by jaruba** [comment]
Now the question is how to explain this in the [Getting started with QML](https://github.com/RSATom/WebChimera/wiki/Getting-started-with-QML) page, as a serious part of it assumes that clicking the button before adding a second MouseArea will not allow you to click it and get the same effect.. which is clearly wrong.

**Comment by jaruba** [comment]
I tried loading WebChimera Player with WebChimera Plugin v0.2.4 (Win) and I get:

    [7320] http://www.webchimera.org/player/themes/sleek/main.qml:391:3: Type Loader.AddMRL unavailable
    [7320] http://www.webchimera.org/player/themes/sleek/components/AddMRL.qml:2:1: module "QtQuick.Controls" is not installed
    [7320] http://www.webchimera.org/player/themes/sleek/components/AddMRL.qml:4:1: module "QtQuick.Controls.Styles" is not installed
    [7320] http://www.webchimera.org/player/themes/sleek/components/AddMRL.qml:2:1: module "QtQuick.Controls" is not installed
    [7320] http://www.webchimera.org/player/themes/sleek/components/AddMRL.qml:4:1: module "QtQuick.Controls.Styles" is not installed

and the infamous black screen. So I can confirm that WebChimera Player does not load on v0.2.4 so this should be the reason why @LukasBombach cannot get it working on Mac. (as v0.2.5 is not yet released on Mac)

**Comment by RSATom** [comment]
Or it's possible use test version: https://dl.dropboxusercontent.com/u/94817236/WebChimera_0.2.5.1_vlc_2.2.0.dmg where `QtQuick.Control` module was already added (and will be good to test it a little)

**Comment by LukasBombach** [comment]
I created a simple repository demonstrating how to write interfaces for WebChimera using nw.js and either QML or HTML / CSS / JavaScript.

Here: https://github.com/LukasBombach/nw-webchimera-demos

**Comment by RSATom** [comment]
@LukasBombach, Thank You!

**Comment by jaruba** [comment]
@LukasBombach That's Great!

I tested it and have a few things to mention though:

"To learn how to write QML, @jaruba wrote a nice tutorial on how to get started with QML on the WebChimera Wiki."

That's very kind of you, but I'm not the original creator of that page, either @RSATom or @gyzerok started it, I just fixed a few minor things on your request.

"On OS X copy the WebChimera.plugin file to the plugins folder of this project in your nw root directory."

People would also need to add:

    "chromium-args": "--load-plugin=plugins/WebChimera.plugin",

to ``package.json`` in order to embed the plugin in the nw app.

"On Windows use the installer that you downloaded to install WebChimera globally."

On Windows, you can also embed the plugin in the app by downloading the zip archive (released with each version of webchimera plugin on [the releases page](https://github.com/RSATom/WebChimera/releases)) and extracting the contents in nw's "plugin" folder.

Then adding this line to ``package.json``:

    "chromium-args": "--load-plugin=plugins\\npWebChimera.dll",

**Comment by RSATom** [comment]
> "chromium-args": "--load-plugin=plugins\\npWebChimera.dll",

@jaruba, will `--load-plugin` work without placing `npWebChimera.dll` to `plugins` folder?

**Comment by jaruba** [comment]
No, I mentioned that it would require downloading the zip archive and extracting it to the plugins folder.

**Comment by RSATom** [comment]
> That's very kind of you, but I'm not the original creator of that page, either @RSATom or @gyzerok started it, I just fixed a few minor things on your request.

@gyzerok was initial author of it

**Comment by RSATom** [comment]
> No, I mentioned that it would require downloading the zip archive and extracting it to the plugins folder.

Ask another way just to be sure I was 100% clear: if `--load-plugin=npWebChimera.dll` will work if we place `npWebChimera.dll` near the nw.exe? Or it has to be placed to `plugins` folder (and `--load-plugin=plugins\npWebChimera.dll` used)?

**Comment by jaruba** [comment]
Oh, it can also be:

"chromium-args": "--load-plugin=npWebChimera.dll",

to load it outside ``plugins`` folder, but the thing I don't like about this approach is that WebChimera Plugin also has a ``plugins`` folder, so moving the extracted files to the nw's root directory may cause some issues as it also uses that same folder.

**Comment by RSATom** [comment]
Hm... your are right.

**Comment by jaruba** [comment]
@LukasBombach I've also added a link to your repository at the end of [Getting Started with QML](https://github.com/RSATom/WebChimera/wiki/Getting-started-with-QML) and the Github Sources section on [WebChimera Wiki](http://wiki.webchimera.org/WebChimera_Wiki#Github_Sources)

**Comment by LukasBombach** [comment]
@jaruba Thank you. I updated the readme and provided package.json files for windows and os x https://github.com/LukasBombach/nw-webchimera-demos

**Comment by LukasBombach** [comment]
I have written a blog post on the whole thing, a step by step guide on how to set it up. http://lukasbombach.de/2015/04/06/videos-with-node-webkit.html

**Comment by jaruba** [comment]
@LukasBombach Great article. Think it would be cool to have a demo for a ready-made basic toolbar in QML and in CSS+JS too. Should be pretty helpful to new users. :)

**Comment by RSATom** [comment]
We must have link to this article in our wiki!

**Comment by jaruba** [comment]
@RSATom I added it to the Plugin Documentation:
http://wiki.webchimera.org/WebChimera_Wiki#Plugin_Documentation

**Comment by RSATom** [comment]
@jaruba Great! :)

**Comment by jaruba** [comment]
@LukasBombach If you want, you can check out [the example](http://ask.webchimera.org/413/not-able-to-exit-full-screen?show=418#a418) I put for this answer to add double click to toggleFullscreen and Esc to exit fullscreen to your article and repo.

**Comment by LukasBombach** [comment]
@jaruba I will add some advanced examples. But it's gonna take me some time, I'm pretty busy right now.

**Comment by jaruba** [comment]
@LukasBombach No one is in a hurry. Rome wasn't built in a day. :)
