### ISSUE TITLE
.MediaPlayerStateChanged in JS API

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#101]
Would need something like ``.MediaPlayerStateChanged( state )`` if it is possible.

**Comment by RSATom** [comment]
`stateChanged` signal already exists

**Comment by jaruba** [comment]
I knew there was one in the QML API, but didn't find a state changed event in the [JS API](https://github.com/RSATom/WebChimera/wiki/JavaScript-API)

**Comment by RSATom** [comment]
ah... understand, ok.
