### ISSUE TITLE
.focus() in the JS API

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#102]
There is sometimes a need to focus to player on demand.

Is something like ``.focus()`` possible in the JS API?

**Comment by RSATom** [comment]
It will not work on Mac OS X...

**Comment by jaruba** [comment]
does the html ``<object>`` tag need focus from the browser page on Mac OS X?

or is it just not possible?

**Comment by RSATom** [comment]
> does the html <object> tag need focus from the browser page on Mac OS X?

Is it possible set focus to <object> via JS? If yes - it should work already now (on Mac OS X).

**Comment by RSATom** [comment]
> or is it just not possible?

the problem is plugin on Mac OS X does not have any window, so only browser can control focus state.

**Comment by jaruba** [comment]
@RSATom http://www.w3schools.com/jsref/met_html_focus.asp

So it's pretty possible that this is only needed on Windows anyway.

**Comment by jaruba** [comment]
but you might need to call it differently then ``.focus()``, as that is the exact name of the JS native function too, and it is called with ``.getElementById()`` on the object tag also. :)

**Comment by RSATom** [comment]
Ok, will implement it for Windows. Thanks!

**Comment by RSATom** [comment]
tried

    document.getElementById("plugin_inst_1").focus();

on http://rsatom.github.io/WebChimera/demos/basic/basic_1.htm and get

    TypeError: document.getElementById(...).focus is not a function

it seems `focus()` is not valid for `<object>`?

**Comment by jaruba** [comment]
From what I've read online it should work for object tags too.

Try the function from this answer: http://stackoverflow.com/questions/7921690/how-do-i-make-my-flash-object-get-focus-on-load#answer-13674793

As flash elements also use the object tag.

**Comment by RSATom** [comment]
Thanks, it looks tricky...

**Comment by jaruba** [comment]
I think this could be very useful, even with support just for windows.

Why I think this is needed: in node-webkit it is most likely that on some pages the player will be the main object on the page. If the node-webkit window is selected (focused), then the player would still need to be selected for the hotkeys to work. With ``.focus()``, the player could be focused on page load and on window focus for these cases.

**Comment by RSATom** [comment]
If don't think about Mac and Linux it could be little easer.

**Comment by jaruba** [comment]
It could also be useful for web use too (like our demo pages), the only thing on those pages is the player, it should be focused when loaded and on tab focus.

**Comment by jaruba** [comment]
Also useful mostly in NW.js or Electron, https://github.com/RSATom/WebChimera.js is the clean solution for this.
