### ISSUE TITLE
How to embed plugin into nw.js (node webkit) application

### ISSUE THREAD

**Issue by kevkha** [RSATom/WebChimera#103]
I thought I saw this before but could not locate it now. Where can I obtain this instruction? Thanks.

**Comment by jaruba** [comment]
https://github.com/jaruba/WebChimeraPlayerNW

Is the project page.

You can [download it here](https://github.com/jaruba/WebChimeraPlayerNW/archive/master.zip) for windows, and just run nw.exe. Then edit the html files as you wish.

For Mac, read the Readme.md on the project page for step by step instructions.

**Comment by RSATom** [comment]
> I thought I saw this before but could not locate it now.

It was empty wiki page and I removed it since nobody fill it... Please look @jaruba's example.

**Comment by kevkha** [comment]
Thanks much guys!

**Comment by jaruba** [comment]
I updated WebChimera Player from v1.08 to v1.11 in the NW repo.

Same [download link](https://github.com/jaruba/WebChimeraPlayerNW/archive/master.zip) as before.

**Comment by kevkha** [comment]
Like clicked :-) Thanks.
