### ISSUE TITLE
How about licensing when using with nw.js

### ISSUE THREAD

**Issue by LukasBombach** [RSATom/WebChimera#104]
Hi,

this is a question that has probably been asked often, but I am unsure about it. So WebChimera is licensed as LGPL-2.1. What does that mean for nw.js (node-webkit) applications including WebChimera? 

As far as I understand it, the application can be distributed as closed-source, also commercially, but the source code *of WebChimera* must be made accessible along with the application. Is that correct?

That being said (or asked), I just wanna say I don't plan on releasing a closed-source or commercial project, but I wanna write a blog post about nw.js and WebChimera.

Cheers

**Comment by RSATom** [comment]
> As far as I understand it, the application can be distributed as closed-source, also commercially, but the source code of WebChimera must be made accessible along with the application. Is that correct?

Yes, exactly. Especially if you will made some changes in WebChimera Plugin you should share your changes somehow. And you should mention using WebChimera Plugin somewhere (site or docs or about etc.).

**Comment by RSATom** [comment]
@jaruba, what license `WebChimera Plugin` have?

**Comment by jaruba** [comment]
ofc it is :)

**Comment by LukasBombach** [comment]
Thanks guys
