### ISSUE TITLE
How to change default asceptratio to 16:9 :

### ISSUE THREAD

**Issue by drenhajdari** [RSATom/WebChimera#106]

**Comment by drenhajdari** [comment]
I tried to change on setting from Default to 16:9 or 4:3 but no changes on Players

**Comment by fapeci** [comment]
It is the same as this one
https://github.com/jaruba/WebChimeraPlayer/issues/6

**Comment by jaruba** [comment]
What video/audio url are you using? Could you give me a sample code that isn't working for you?

**Comment by RSATom** [comment]
no answer within reasonable time
