### ISSUE TITLE
Feature Request - nw.js 64-bit support

### ISSUE THREAD

**Issue by sunjam** [RSATom/WebChimera#110]
Wondering about the status of this after looking through your past Github issues and wiki.  I'm on Windows.

**Comment by RSATom** [comment]
Official VLC releases are 32-bit. Why do you need 64-bit?

**Comment by sunjam** [comment]
I'm curious about WebChimera being used with [Tagspaces](https://github.com/tagspaces/tagspaces), which is built on both 32-bit and 64-bit versions of nw.js.  It is a file manager that currently includes basic media playback

**Comment by RSATom** [comment]
TBH I don't see any reason why this application could require 64-bits.

But OK, I understand your point. But please understand me too: release every new version takes much time, and build multiple plugin version for one platform will require even more time. Unfortunately I very limited in it. One obvious solution I want implement long time - organize dedicated build server for all platforms (look https://github.com/RSATom/WebChimera/issues/15) - but I still have no hardware for it.

**Comment by RSATom** [comment]
With existence of `WebChimera.js` don't see any reason to keep it open...
