### ISSUE TITLE
Image frozzen on Firefox with high resolution

### ISSUE THREAD

**Issue by desmat92** [RSATom/WebChimera#112]
Hi, 
I'm using WebChimera to display an image with an high resolution (1890x840, MPEGTS over UDP generated with ffmpeg) on Firefox. With this computer : 
- Xeon E5-2603 v2 @ 1.8GHz 4 cores
- RAM 16Go
- SSD 128Go
- HD 3To 7200rpm
- Carte graphique AMD FirePro V3900 1GB

The image freezes every 4-5 seconds during 4-5 seconds...

The test with a lower resolution gives a better result (1280x568), and there is no freeze with the vlc plugin and the high resolution.

**Comment by RSATom** [comment]
Could you please explain in the little more details how exactly this freeze looks like?
What CPU load do you have on each of your 4 cores?

**Comment by RSATom** [comment]
And do you have enabled debug mode in plugin?

**Comment by desmat92** [comment]
About 25% of CPU load.
See logs : http://desmat92.free.fr/debugview_webChimera.LOG
Thanks

**Comment by desmat92** [comment]
All my cpus are working.
The debug mode doesn't impact this behaviour.

**Comment by RSATom** [comment]
> All my cpus are working.

I didn't mean you have broken CPU or something similar, I mean some algorithms could not use multiple cores at the same time, and then you will have 100% load on one CPU core and ~0% load on all others. And you will have bottleneck in performance of one core, no matter how many cores you have (but don't say it's your case, just one possible reason)

> Edit: works better with network-caching to default value, i was set to 300... And i wasn't set it when i used vlc plugin...
> I'm a trying to view a real time stream, but the "buffer" parameter seems to have no effect.
> Sorry for loosing your time.

Never mind, I'm always glad to know one else man use our work.

So if you found the reason of problem, could you please clothe this issue?

**Comment by jaruba** [comment]
@desmat92 Are you sure the "buffer" parameter doesn't work for you? I tried:

http://editor.webchimera.org/c/1429785044

And it correctly adds "network-catching" to the object tag, the video is also clearly loading a lot slower.

**Comment by desmat92** [comment]
@RSATom : i wanted to say that the 25% was departed on the 4 cores, and no one is at 100%.
Trying an other test, with a "live" stream mpegts over udp and a "vod" stream mp4. And after i close this issue

@jaruba : if the "buffer" parameter add "network-caching" to the object tag, then i'm going to have the same problem, So i left the default value.

**Comment by desmat92** [comment]
It's ok for me, thanks for your help
