### ISSUE TITLE
Taking snapshots with WebChimera Plugin

### ISSUE THREAD

**Issue by TeeJiiAl** [RSATom/WebChimera#114]
It would be great if WebChimera had a feature which would make possible to take video snapshots.

**Comment by RSATom** [comment]
Thank you for request.

Do you need it within QML, JS or both?

**Comment by jaruba** [comment]
@RSATom Are you planning to add this to the QML, JS API?

I have been asked before by another user if the player can take screenshots.

**Comment by RSATom** [comment]
It's possible for both, I just don't sure what picture format use for JS side...

**Comment by RSATom** [comment]
http://doc.qt.io/qt-5/qquickitem.html#grabToImage

**Comment by jaruba** [comment]
*I just don't sure what picture format use for JS side...*

Use PNG if you can, it has the best compression.

**Comment by TeeJiiAl** [comment]
Hello, JS is preferred. We have no experience with QML, but if it works better with that we will look into that.

I also think PNG would be good idea.

**Comment by RSATom** [comment]
@jaruba I think it's possible.

@TeeJiiAl, How do you plan to use this picture? I should know it to select most suitable implementation.

**Comment by jaruba** [comment]
@RSATom Couldn't you send it back as string encoded in base64?

That way it could could be either saved to a file or displayed directly from the web page. But the function to call the screenshot should be async in this case, to not freeze the page until the process is finished.

**Comment by RSATom** [comment]
@jaruba, base64 - yep, without any problem I think.

**Comment by TeeJiiAl** [comment]
The player would be part of the metadata management system, which provides acces to VOD server. Files are in H.264 format wrapped in TS. Files are streamed to clients. Snapshots would be used capturing end titles of the programs for cataloguing purposes. Right now we use web plugin provided in VLC 2.1.5.

**Comment by RSATom** [comment]
@jaruba, Does it has any meaning within QML? Cite from http://doc.qt.io/qt-5/qquickitem.html#grabToImage:
>Note: This function will render the item to an offscreen surface and copy that surface from the GPU's memory into the CPU's memory, which can be quite costly. For "live" preview, use layers or ShaderEffectSource.

i.e. layers and ShaderEffectSource could be used for something similar (but don't sure how exactly yet)

**Comment by RSATom** [comment]
> Snapshots would be used capturing end titles of the programs for cataloguing purposes.

i.e. you plan send it to server, right? So base64 encoded png will go good enough for you, right?

**Comment by jaruba** [comment]
@RSATom I'm not sure if there is any good reason to have it in QML ftm.

I'm thinking it would be nice to have a "Screenshot" option in the context menu of the player, but even if it would have this option, in all circumstances it would still need to send the image back to JS in order to either save it to the disk (node-webkit) or prompt the visitor to download it (web use). So it could be enough to have it only in JS.

**Comment by TeeJiiAl** [comment]
They would be stored in local workstations for now, but maybe in later phase possibilty to store them in MMS. As long as you can read text from the image (end titles), it is fine.

**Comment by RSATom** [comment]
Ok, then I think it will be easy enough (I hope). Scheduled to next release.

**Comment by TeeJiiAl** [comment]
Great!

**Comment by RSATom** [comment]
Btw, what OS do you use?

**Comment by TeeJiiAl** [comment]
Mostly Windows 7, few use OS X.

**Comment by RSATom** [comment]
It's good, since initially I will start implement it on Windows.

**Comment by appollosputnik** [comment]
Is this features grabImage implemented Dear Jaruba? If yes then please tell me in which version & how to build it if it is differently needs to be built.?

**Comment by jaruba** [comment]
@appollosputnik

I can't implement it, it needs to be available in WebChimera Plugin, so @RSATom will need to make it when he finds some time.

But I see this feature is pretty famous though, someone asked me about it even before this request was ever created.

**Comment by RSATom** [comment]
This task is still on the begining of my todo list, but unforunatly I'm very limited in free time...

**Comment by appollosputnik** [comment]
@RSATom  May I know approx by when you're planning to implement in plugin? I need it urgently so if you could give me some hints if I can try myself to implement it it will be highly appreciated. Can you do that ? How I should proceed about it.

**Comment by RSATom** [comment]
To solve this task we require function which will convert [QmlVlcI420Frame](https://github.com/RSATom/QmlVlc/blob/master/QmlVlcVideoFrame.h) to `QImage`, or at least `RGB` array. I'm already solved this task but with shaders: https://github.com/RSATom/QmlVlc/blob/master/SGVlcVideoNode.cpp#L65, now the same should be done on CPU.

**Comment by appollosputnik** [comment]
@RSATom  - O so good RSATom. Now I think Jaruba can take it to do it in CPU?
@jaruba - Do you think dear Jaruba that you can include it in Plugin & fetch it to CPU?

Please update me sir.

**Comment by RSATom** [comment]
@appollosputnik, you didn't understand. It's not implemented yet. I just tell how it should be done.

**Comment by RSATom** [comment]
Implementation on shaders could not be used in this case, so it should be reimplemented.

**Comment by RSATom** [comment]
@appollosputnik, do you have some deadline?

**Comment by appollosputnik** [comment]
OIC. Yes @RSATom I have deadline till this week. Is it possible to do it by the end of this week. I will really appreciate it.

I am really very happy with other features & you guys support. You guys are into fantastic project doing. I would like to make some donation on this project to grow it bigger. I will always be in sync with this project. Please give me your official PayPal ID where I transfer my donation.

Please try if you can implement it by the end of this week.? Let me know if not how long time it may take?

Regards
Sujan

**Comment by RSATom** [comment]
@appollosputnik, you could see `donate` button on http://www.webchimera.org/ or use my email (RSATom at gmail dot com) as PayPal ID

Is it ok if it will be ready to monday (May 25)?

**Comment by appollosputnik** [comment]
Ok I will do it using either.

Yes I think I will be OK by Monday if you can make it. I will extend my deadline a bit. It will be perfectly Ok. Please start with it as per your schedule. And post a message when it's done with the guidelines of usage. I thanks you both @RSATom  and @jaruba  for your support, it's highly appreciated.

Regards
Sujan

**Comment by RSATom** [comment]
Ok, Maybe I will do it earlier, just don't want promise.

**Comment by RSATom** [comment]
> Ok I will do it using either.

You could use any, it's the same PayPal ID.

**Comment by appollosputnik** [comment]
Ok dude take your time Update me when I can use it.

Regards
Sujan

**Comment by RSATom** [comment]
test version: https://dl.dropboxusercontent.com/u/94817236/WebChimera_0.2.7.2_vlc_2.1.5.msi
API changes (will add it to wiki on release):
Qml:  added global function `takeQmlItemShot( shotId, qmlItem )`
JS: added event `QmlItemShot( shotId, qmlItemShot )`

Shot could be taken from any visual Qml item. If you need take shot from video - you should pass `id` of `VlcVideoSurface`.

**Comment by jaruba** [comment]
@RSATom Great job! I will start testing it tomorrow.

I wonder if it will work to take a screenshot of ``VlcVideoSurface`` while it is [scalled](http://doc.qt.io/qt-5/qml-qtquick-scale.html).

**Comment by appollosputnik** [comment]
@RSATom Excellent job. I am checking it now. 
Thanks a lot sir.

Regards
Sujan

**Comment by RSATom** [comment]
@jaruba, it should work with any visual item

**Comment by appollosputnik** [comment]
@RSATom  I have created a button on toolbar like this
				// Start SnapShotNext Button
				Loader.ToolbarButton {
				        id: snapBut
					icon: "Snap"
					iconSize: fullscreen ? 8 : 7
					anchors.leftMargin: 1
					glow: ui.settings.buttonGlow
					onButtonClicked: buttons.clicked("snapshot");
				}

And in Buttons.qml I added this code:
		if (action == "snapshot") if (typeof settings.preventClicked[action] === "undefined") {
			QmlItemShot( VlcVideoSurface, base64)
		}

This should work right in version 0.2.7.2 ? But it's not working.

1st of all I am not able to see any video in version 0.2.7.2, only sound is coming.

**Comment by RSATom** [comment]
You use it wrong. Please wait while @jaruba add shot support to player, I think he will do it soon.

**Comment by jaruba** [comment]
@RSATom Please check [gitter chat](https://gitter.im/RSATom/WebChimera), there is a bug with ``WebChimera Plugin v0.2.7.2``.

**Comment by jaruba** [comment]
Also, please confirm that I understand the usage of the new function/event.

    takeQmlItemShot( shotId, qmlItem )

Should be used in QML in order to make a screenshot. ``qmlItem`` will be the ``id`` of the QML component that will be captured in the image and ``shotId`` is simply an integer that will help identify the newly created image (as creating the image is async).

When the image has been constructed, then:

    QmlItemShot( shotId, qmlItemShot )

will be triggered in JavaScript, ``shotId`` will be used in order to identify the created image with the selected integer value that was set in ``takeQmlItemShot()`` and ``qmlItemShot`` will be a ``data:image/png;base64`` encoded string.

Is this presumption correct?

**Comment by RSATom** [comment]
Yes, it's correct

**Comment by RSATom** [comment]
But if you try take next shot before  `QmlItemShot` arrives - previous shot will be lost.

**Comment by RSATom** [comment]
Btw, maybe you have some suggestions about this API?

**Comment by appollosputnik** [comment]
@RSATom Seems to be perfectly fine.  Just one suggestion is it too difficult to give an option for encoding in JPEG format also.  Many users prefer JPEG. If it is not too difficult please try to include in the option of saving the image.

**Comment by jaruba** [comment]
@appollosputnik

The screenshot should not be JPEG, it is best for it to be PNG. The reason for this is that PNG has a lot better compression.

Images that have 3MB in JPEG format might only have 700kb (or maybe even less) in PNG format and there is absolutely no visual difference between the images. PNG will download A LOT FASTER to the user's PC and use less bandwidth from your server. There are just to many advantages to using PNG and it is always recommended to use PNG over JPEG in all web based projects.

**Comment by jaruba** [comment]
> Btw, maybe you have some suggestions about this API?

> But if you try take next shot before QmlItemShot arrives - previous shot will be lost.

Then why even add a ``shotId`` if it cannot support multiple parallel instances of taking screenshots? I don't see any reason for it..

And if ``shotId`` isn't required, maybe ``qmlItem`` could default to ``vlcPlayer`` if nothing is set? That would further simplify things.

**Comment by RSATom** [comment]
@appollosputnik, I'm agree with @jaruba, `png` is better than `jpeg` by many reasons.

**Comment by RSATom** [comment]
> Then why even add a shotId if it cannot support multiple parallel instances of taking screenshots? I don't see any reason for it.

The reason is simple, taking shot started on QML side, but result arrives at JS side - so it's possible shot will require some additional info to handle it right way on JS side.

But I have idea how I should change shot API. Maybe it was wrong idea init operation and get result on different sides (QML vs JS). Maybe we should have `takeQmlItemShot( qmlItem )` function and `qmlItemShot( qmlItemShot )` event both on QML side. And after that it will be developer decision if it required send shot to JS side with `QmlStringMessage` for example.

**Comment by jaruba** [comment]
@RSATom makes sense, as QML is on the client side it shouldn't add any significant delay to the process, just gives more programmatic control over the process.

With just ``takeQmlItemShot( qmlItem )`` and ``qmlItemShot( qmlItemShot )`` in QML, I can easily make something like ``.takeScreenshot()`` function and ``.catchScreenshot()`` event in WebChimera Player's JavaScript API.

**Comment by appollosputnik** [comment]
@RSATom  Ok, that will be fine. we will work with PNG that will be better.

Thanks a lot for all your dear @RSATom  and @jaruba

**Comment by RSATom** [comment]
@jaruba, ok, working on it right now.

**Comment by appollosputnik** [comment]
@RSATom @jaruba  Ok dudes take your time.

**Comment by RSATom** [comment]
new test version: https://dl.dropboxusercontent.com/u/94817236/WebChimera_0.2.7.3_vlc_2.1.5.msi

shot API was changed. Now all related members are on QML side:
* `takeShot( qmlItem )` - global function
* 'shotReady( shot )' - global signal

usage example: https://gist.github.com/RSATom/11d39328069282ff8f65

**Comment by appollosputnik** [comment]
@RSATom  Dear please give an option of saving it in JPEG format. I need it it's very important  for me. If not possible tell me, I will have to convert it from html if possible at run time. But I need it either in plugin or player. Please let me know if you can help me in that.

I am testing the latest version, thanks a lot for the fix.

Regards
Sujan

**Comment by jaruba** [comment]
@appollosputnik 

You can convert a ``data:image/png;base64`` to ``data:image/jpeg;base64`` with JavaScript as described in this answer:

http://stackoverflow.com/questions/17590136/base-64-png-string-to-base-64-jpg-using-java-or-javascript#answer-19286473

**Comment by appollosputnik** [comment]
@jaruba that will be great, Jaruba, is it possible for you make an  API for JPEG after capturing the actual PNG image, in webchimera.js file?

Then I will call that in Buttons.qml on click of some button on the toolbar panel.

Regards

**Comment by jaruba** [comment]
@appollosputnik 

I will not add it to webchimera.js, but I can probably show you how to do it. Also, do you need for the screenshot button to be in the toolbar?

I would personally add it in the context menu (from right click) and as a hotkey. Would that be ok for your needs?

**Comment by appollosputnik** [comment]
@jaruba  Ok Jaruba please give me guidance how I can do it dynamically in my player.html file, that should be fine.

Context menu will create problem Jaruba, because while taking shot if the menu appears that may also appear in the picture right?

Better option would be a dynamic button on left or right tool bar panel. That should be fine.

Regards
Sujan

**Comment by jaruba** [comment]
@appollosputnik The screenshot is not made of the entire player, we can choose exactly what element will be extracted from the player and added in the image. In this case, we will only screenshot the video feed, none of the user interface items, so the toolbar, context menu, etc. will not appear in the picture.

So is it alright then to add it to the context menu and as a hotkey (``CTRL`` + ``S``)? Personally I don't want to add it to the toolbar, there are already a lot of buttons in the toolbar and I still want to leave some space there for people that want to add their own custom buttons.

If I add it to the context menu and the hotkey then it will always be available for you in the same way in all future versions of WebChimera Player too, so you can update easily to newer versions of the Player later on.

**Comment by appollosputnik** [comment]
@jaruba  OK dear Jaruba it'll be fine I think. Then add it to the context menu with  a hot key. That will be great.
Thanks

**Comment by appollosputnik** [comment]
@jaruba & @RSATom  Please try to release the plugin & player by this weekend if possible. But it will be fine if you do that by coming Monday also.

Thanks a lot.

Regards
Sujan

**Comment by RSATom** [comment]
@appollosputnik, how about donation/bounty?

**Comment by RSATom** [comment]
@jaruba, maybe it worth change function/signal names to `takeSnapshot( qmlItem )` and `snapshotReady( shot )` ? What do you think? it seems `shot` is wrong word for this feature :)

**Comment by appollosputnik** [comment]
@RSATom  Dear Sergey I will make surely some donation by the end of next week. Don't worry about that at all. I will be with you guys for long term.

@jaruba  Dear Alexandru please make a release of the complete version with the source so that I can start using it.

I really appreciate you guy's good work, I am with you for long term don't worry. We will help each other.

Regards
Sujan

**Comment by jaruba** [comment]
@RSATom It's not really necessary, but these lines in your demo:

    onTriggered: takeShot( videoOutput );
    target: plugin;
    onShotReady: fireQmlStringMessage( 0, shot );

Are really funny when you first read them.. :)))

**Comment by RSATom** [comment]
yea, it's funny :) anyway I think I will change it. so please don't release new Player version before I release plugin. If you already tested it, I even could do it today.

**Comment by jaruba** [comment]
@appollosputnik I am working on a solution for you but converting png to jpeg is proving more difficult then I previously anticipated.

**Comment by jaruba** [comment]
> I wonder if it will work to take a screenshot of VlcVideoSurface while it is [scalled](http://doc.qt.io/qt-5/qml-qtquick-scale.html). (I guess it should)

@RSATom It does not take a screenshot of the scalled image, it screenshots the entire image as if it wore not scalled.

@appollosputnik I finished the screenshot feature in the player, you can download it from:
http://webchimera.org/samples/WebChimeraPlayer-screenshot.zip

It converts the image to jpeg automatically before prompting for download. I also added a Digital Zoom demo to the package.

But I'm guessing you need it to screenshot the video exactly where you zoomed in on the video? If so it will not do that correctly as I've mentioned above it does not take into consideration that the video is zoomed in..

It's not impossible to make it screenshot the zoomed image.. but it's not easy to do either.. I really hope that you do not need it to screenshot with the zoom feature.. Otherwise it will take some serious coding to make that possible..

**Comment by RSATom** [comment]
@jaruba, did you make zoom by place `VlcVideoSurface` into `Rectangle` with `crop=true`?

**Comment by jaruba** [comment]
@RSATom no, I'm using ``.scale.origin.x`` and ``.scale.origin.y``. [Scale QML Type](http://doc.qt.io/qt-5/qml-qtquick-scale.html)

**Comment by appollosputnik** [comment]
@jaruba Thanks Dear Alexandru I am testing it right now.

@RSATom Dear Sergey can you give me the source of Plugin version 0.2.7.3? Then I can use it according to my need.

Regards
Sujan

**Comment by appollosputnik** [comment]
@jaruba  I tested it Jaruba it's awesome, fantastic, you guys made it so beautiful. Thanks a lot. I will surely make some good donation, please wait till next week. Keep up the good work we will build bright future with Chimera.

@RSATom  Dear Sergey it will be great if you could give me the source of Plugin version 0.2.7.3 soonest. I can proceed forward then.

Keep it up..Thanks
Regards
Sujan

**Comment by RSATom** [comment]
@jaruba, you could try create second `VlcVideoSurface` and place it into `Rectangle` with `crop=true`. After that pass `id` of rectangle to `takeShot` - in this case you should get only visible part of video frame.

**Comment by RSATom** [comment]
@appollosputnik, current master branch = version 0.2.7.3

**Comment by appollosputnik** [comment]
@RSATom master branch is still showing version 2.7.1 Dear can you post the link ?

**Comment by RSATom** [comment]
I didn't tag 0.2.7.3, so just look to the latest commit at the master branch. Btw, I will release v0.2.8 within a hour, so you could wait a little - but you will have to change qml since I've changed snapshot function and signal names a little.

**Comment by RSATom** [comment]
I've just released `WebChimera v0.2.8` (only for Windows). 
**Important:** 
* `takeShot( qmlItem )` function was renamed to `takeSnapshot( qmlItem )`
* `shotReady( shot )` signal was renamed to `snapshotReady( snapshot )`

updated usage example: https://gist.github.com/RSATom/ccc002c35e8fe1303306

**Comment by appollosputnik** [comment]
@RSATom Thanks a lot dear Sergey.

@jaruba  Please update me Alexandru which version of player shall I use? I think the one above you  posted is more active right compatible with 0.2.8?

Please share the compatible version of player.

Regards
Sujan

**Comment by RSATom** [comment]
@appollosputnik, you could fix it yourself, just change function, signal and signal argument names to mentioned above. Logic didn't changed.

**Comment by appollosputnik** [comment]
@RSATom  Ok dude. Let me do that. Please give me the link of VLC version 2.2.1 for Chimera compilation which I need to keep src/Win/Wix folder. I am not able to get it. My build is failing.

**Comment by RSATom** [comment]
http://get.videolan.org/vlc/2.2.1/win32/vlc-2.2.1-win32.7z

**Comment by appollosputnik** [comment]
@RSATom Thanks a lot dude.

**Comment by appollosputnik** [comment]
@RSATom @jaruba  There is no 'shotReady' in player it is 'onShotReady'

'onShotReady' should be changed to 'snapshotReady' right ?

**Comment by jaruba** [comment]
@appollosputnik 

http://webchimera.org/samples/WebChimeraPlayer-screenshot.zip

This one now supports ``WebChimera Plugin v0.2.8``

**Comment by appollosputnik** [comment]
@jaruba  Thanks a lot dude, let me try it.

Regards
Sujan

**Comment by jaruba** [comment]
@appollosputnik Is taking screenshots when the Player is in zoomed mode important for your project? Because I would delay it for a bit if it is not crucial.

@RSATom Is this going to be implemented soon on Mac / Linux? Or should I check for platform for this feature before committing to master?

**Comment by RSATom** [comment]
It already should work on all platforms, I just need find some time to build mac version.

**Comment by RSATom** [comment]
so you could just test v.0.2.8 if you wish.

**Comment by jaruba** [comment]
@RSATom Btw, I managed to make a good converter for base64 images in JavaScript by inserting the image into the page then drawing it on a canvas and exporting the canvas to a base64 string again and choosing any image format I want.

Thinking of making a github repo with this solution as I haven't really found any easy way to do it while checking google. :)

**Comment by RSATom** [comment]
do you mean canvas accept base64 encoded images directly?

**Comment by jaruba** [comment]
not directly, I put base64 encoded images in a <img> tag first, then I use ``.drawImage()`` to draw the <img> tag on the canvas after which I use ``.toDataUrl()`` to convert the canvas to a base64 encoded image.

**Comment by RSATom** [comment]
now understand, thanks for explain.

**Comment by appollosputnik** [comment]
@jaruba  Dear Jaruba taking screenshot when zoomed is also important dude. Please try if you can do it , I can understand your time is too hectic but without that feature will not take complete shaped dude. Please take some time try to include it in player.

Is it the work to be done in player or plugin.?

**Comment by jaruba** [comment]
I'm not sure if it can be done in the plugin, but in the player it is very complicated from my point of view. ``Scale`` uses totally different parameters then those needed for ``crop: true``, I actually tried to do it with ``crop: true`` in the past and failed terribly.

``Scale`` actually saved me as it worked a lot better and it was a lot easier to use for this feature. Needing to do it all again with ``crop: true``.. I'm not even sure how long it will take..

**Comment by appollosputnik** [comment]
@jaruba  You're right. I am not sure whether it will be easier in plugin or player. But the viewing volume has to be scaled equally with respect to zoom before capturing the container. It will be some what difficult I understand. But you can best judge. 

Just try if it could be done shortly or take some time as long as you need, I will try to adjust without this for time being. But remember this features makes it complete in full shape. 

Regards
Sujan

**Comment by RSATom** [comment]
@jaruba, is there any online demo available with zoom feature?

**Comment by jaruba** [comment]
@RSATom only here atm: http://webchimera.org/samples/WebChimeraPlayer-screenshot/digital_zoom.html

**Comment by RSATom** [comment]
Thanks, it's enough.

**Comment by jaruba** [comment]
package that includes this demo here: http://webchimera.org/samples/WebChimeraPlayer-screenshot.zip

**Comment by RSATom** [comment]
Thank you, Alexandru.

**Comment by cute40617** [comment]
Hi, when I try out the screenshot demos on IE11 not working, but Chrome OK, What is a solution for this?

**Comment by jaruba** [comment]
does the console log give any errors?

**Comment by cute40617** [comment]
IE11 not any response
Chrome get one jpg file
Operating environment is Win8.1 and IIS

**Comment by RSATom** [comment]
@jaruba, IMHO it could be only a problem in png -> jpg transform. btw, did you do this transform mandatory or optional?

**Comment by cute40617** [comment]
mandatory

**Comment by jaruba** [comment]
But I don't think the conversion is the problem, the highest chance is that the javascript downloader I made for it is bugged in IE. The problem is that it might not even be possible to fix it as I did some serious voodoo to be able to download an unexisting file from the browser. :)))

This is also the reason I didn't push the screenshot commit to the master branch yet, I'm really unsure of the implementation.. Had to use a lot of hackary that I made myself and am unsure of to make this work correctly. If it's a problem with the conversion, then it's easily fixable, if it's a problem with the downloader then it might not even be possible to fix it.

**Comment by jaruba** [comment]
@cute40617 You can try to disable the conversion in the code to see if that works in IE too.

Just open ``/player/webchimera.js`` with any text/code editor and look at lines 796-840, the code will be:

		wjs(newid).catchEvent("QmlMessage",function(event) {
			if (event.substr(0,10) == "[snapshot]") {
				console.log(event);
				var snapshot = event.replace("[snapshot]","");
				var pngSnapshot = "data:image/png;base64,"+snapshot;

				var image = document.createElement("img");
				document.body.appendChild(image);
				image.style.display="none";
				image.src = pngSnapshot;
				image.onload = function() {
					var canvas = document.createElement("canvas");
					canvas.style.display="none";
					canvas.width = image.width;
					canvas.height = image.height;
					document.body.appendChild(canvas);
					var ctx = canvas.getContext("2d");

					ctx.drawImage(image, 0, 0, image.width, image.height);

					var jpgSnapshot = canvas.toDataURL('image/jpeg');

					var a = document.createElement("a");
					document.body.appendChild(a);
					a.style.display="none";
					a.href = jpgSnapshot;
					a.download = "snapshot.jpg";
					a.click();
					image.remove;
					canvas.remove;
					a.remove;
				};
				// end convert
			
    // download as png
				
    //				var a = document.createElement("a");
    //				document.body.appendChild(a);
    //				a.style.display="none";
    //				a.href = pngSnapshot;
    //				a.download = "snapshot.png";
    //				a.click();
    //				window.URL.revokeObjectURL(url);
			}
		});

From this code you need to delete all this:

				var image = document.createElement("img");
				document.body.appendChild(image);
				image.style.display="none";
				image.src = pngSnapshot;
				image.onload = function() {
					var canvas = document.createElement("canvas");
					canvas.style.display="none";
					canvas.width = image.width;
					canvas.height = image.height;
					document.body.appendChild(canvas);
					var ctx = canvas.getContext("2d");

					ctx.drawImage(image, 0, 0, image.width, image.height);

					var jpgSnapshot = canvas.toDataURL('image/jpeg');

					var a = document.createElement("a");
					document.body.appendChild(a);
					a.style.display="none";
					a.href = jpgSnapshot;
					a.download = "snapshot.jpg";
					a.click();
					image.remove;
					canvas.remove;
					a.remove;
				};
				// end convert

and then uncomment everything after this line:

    // download as png

see if that works for you..

**Comment by RSATom** [comment]
> This is also the reason I didn't push the screenshot commit to the master branch yet, I'm really unsure of the implementation..

Can I help you somehow on plugin side?

**Comment by jaruba** [comment]
If @cute40617 can confirm that removing conversion works in IE, then I'll remove conversion only for IE and commit it, otherwise the only thing that would help would be a way to prompt for download, but having something like that in the plugin just seems silly. :)

**Comment by cute40617** [comment]
I tested, is a failure
But the original code, the 823 line has an error occurred
***************************************************************************************
var a = document.createElement("a");
document.body.appendChild(a);
a.style.display="none";
a.href = jpgSnapshot;
a.download = "snapshot.jpg";
a.click();   <<<-------------- Error Message: Data Area Passed to a System Call Is Too Small. image.remove;
canvas.remove;
a.remove;
***************************************************************************************

**Comment by RSATom** [comment]
it's possible implement possibility to choose format of snapshot inisde plugin. And it's possible specify desired size of snapshot. And it's possible extract subpicture from snapshot. Please tell me if you need something like this.

**Comment by jaruba** [comment]
It's what I was expecting.. Don't know any way to fix it, will check though..
