### ISSUE TITLE
Plugin crashes at the end of .m3u8 files

### ISSUE THREAD

**Issue by sclem** [RSATom/WebChimera#118]
The plugin will crash if it reaches the end of a .m3u8 file. An example is this file from apple's website: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8

The MediaPlayerEndReached event is sometimes fired, other times the player hangs on a stop script (unresponsive).

If the event is fired and `wjs(...).plugin.stop()` is called from JS, the plugin crashes immediately if `plugin.state == 6` (ended).

**Comment by RSATom** [comment]
https://github.com/RSATom/WebChimera/issues/63

it's fixed in Vlc 3.0 (unreleased yet)

Btw, why do you still use it? NPAPI already deprecated in Chome, and [will stop working in Firefox too by the end of 2016](https://blog.mozilla.org/futurereleases/2015/10/08/npapi-plugins-in-firefox/)

**Comment by sclem** [comment]
Oh I didn't see that. I will test with a 3.0 nightly. There isn't really any other solution for playing HLS besides flash right now.

**Comment by RSATom** [comment]
I recommend you switch to use desktop app for example based on `NW.js` or `Electron` + `WebChimera.js`
