### ISSUE TITLE
Packaging with VLC 3.0 does not work

### ISSUE THREAD

**Issue by colek42** [RSATom/WebChimera#119]
Replacing the vlc libraries included with the installer with VLC 3.0 libraries causes js error on line 919 of webchimera.js, this.plugin.playlist undefined.

**Comment by RSATom** [comment]
what OS do you use?

**Comment by colek42** [comment]
This is for Windows.  It does not look like anything is compiled against VLC 3.0.

**Comment by RSATom** [comment]
Could you please enable debug mode then, and look debug log with `DebugView`? I think it's just missing some dll.

**Comment by colek42** [comment]
Will do.  Probably going to be a few days before I get back to this.

**Comment by RSATom** [comment]
Btw, why do you use it? Do you know NPAPI will die soon?

**Comment by colek42** [comment]
Yea, we are going to have to move to nw.js.  There will be zero options for
multicast in the browser after firefox depreciates NPAPI.

**Comment by jaruba** [comment]
@colek42 what are you guys building there? :)

**Comment by RSATom** [comment]
@colek42, I suggest you consider use `Electron` instead of `NW.js`. I like much more how `Chromium` integrated with `node.js` in `Electron`. It uses more robust and less error prone way.
