### ISSUE TITLE
Filter - Hue Support [$100]

### ISSUE THREAD

**Issue by avonhack** [RSATom/WebChimera#121]
Would it be possible to modify the video hue as a filter?

**Comment by RSATom** [comment]
Don't understand. `hue` property exist long time: http://wiki.webchimera.org/Plugin_JavaScript_API#Video_object

**Comment by avonhack** [comment]
Hue is present in the API, but changing the value has to effect. All of the other values (saturation, gamma, etc) work fine.

**Comment by avonhack** [comment]
Here is an example where hue doesn't work:
http://editor.webchimera.org/c/1450308833

**Comment by RSATom** [comment]
ok, I'll check.

**Comment by RSATom** [comment]
Are you able build plugin yourself?

**Comment by avonhack** [comment]
Yes. Works great! Can you collect the bounty?

**Comment by RSATom** [comment]
https://www.bountysource.com/issues/29024114-filter-hue-support

> RSATom submitted a claim  but the backer hasn't responded.      3 days ago

**Comment by avonhack** [comment]
Fixed
