### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by creativefull** [RSATom/WebChimera#122]
HI i get error like this .
```
Error: The specified module could not be found.
C:\Users\Windows7\AppData\Local\Temp\nw2940_12978\node_modules\webchimera.js\Release\WebChimera.js.node
```

before i compile my application alright .

**Comment by jaruba** [comment]
wrong repo, this is WebChimera NPAPI, your looking for WebChimera.js:
https://github.com/RSATom/WebChimera.js/issues

**Comment by creativefull** [comment]
OK Sorry for my issue ,.. thnks for your info :)
