### ISSUE TITLE
Video Pop Out?

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#21]
I know this may be far fetched, maybe even impossible, but I'd really love to see Webchimera have this feature at one point.

The video "Windowed Mode" (Pop Out) is a feature of the Divx Web Player:
http://www.divx.com/en/software/web-player/features

A Demo can be seen here:
http://www.divx.com/en/hevc-showcase

When the video goes in Windowed Mode it remains connected to the JS Api of the Page where the Plugin was called and starts directly in Always on Top mode (which is a must, cause we can't set Always on Top from QT QML and don't have the vlc right click options in the video).

This feature really gives Web Players a WOW Factor!

**Comment by jaruba** [comment]
:)

**Comment by RSATom** [comment]
It seems you stopped believing it will be implemented ever :)

**Comment by jaruba** [comment]
Would still be a cool feature, but as WebChimera can be used both on page and locally (with node-webkit), I have very little interest in it anymore. Just takes up space in the open issues for no reason. :)

**Comment by yipperr** [comment]
hey this is really cool but i can't see the demo because the plugin has no support for linux but do you think that a thread opened to discuss on webchimer being being platform and os independent is relavant seeing this being done under the premise that people can add ppapi support to the libvlc and all the other requirment needed to make webchimera equivalent to the divx web player ?

**Comment by RSATom** [comment]
WebChimera has linux support but you have to build it yourself.

ppapi version of WebChimera is almost impossible now, since:
a) there are no `Qt` for `Chrome Native Client`;
b) there are no libvlc for `Chrome Native Client`;

**Comment by jaruba** [comment]
@yipperr 

There's definitely no need to open a discussion about it, accessibility is a prime concern anyway. :)

A ppapi version won't be available, we've been looking into workarounds for this limitation, but an actual version made for ppapi will certainly not be released. (but hopefully, it won't be needed either)

**Comment by yipperr** [comment]
@RSATom 

there are nacl port (Native client) for gstreamer ,ffmpeg 
but without qt in native client the even exisitng port of multimedia frameworks like ffmpeg and gstreamer won't help for webchimera 
if qt was supported it seems qt has a multimedia framework called phonon
http://en.wikipedia.org/wiki/Phonon_(software)

**Comment by yipperr** [comment]
it seems qt is ported to google native client platform 
https://wiki.qt.io/Qt_for_Google_Native_Client
the qt quick git source
https://github.com/msorvig/qt5-qtdeclarative-nacl

**Comment by RSATom** [comment]
@yipperr, https://forum.qt.io/topic/51735/qtquick-2-for-nacl - I don't want use not supported officially qt5 port, since it could take huge amount of time, which I don't have.

**Comment by yipperr** [comment]
i see the github page make no mention on the status of the port also

**Comment by Zzzen** [comment]
> b) there are no libvlc for Chrome Native Client;

What do you mean? I cannot use libvlc on Chrome Native Client? I need to play rtsp video on XP, it would another disaster if NPAPI is the only option. @RSATom

**Comment by RSATom** [comment]
> What do you mean? I cannot use libvlc on Chrome Native Client?

I mean libvlc didn't ported to Chrome Native Client yet.
