### ISSUE TITLE
Plugin area preload color

### ISSUE THREAD

**Issue by gyzerok** [RSATom/WebChimera#37]
Now before QML skin provided to an object tag is loaded by the plugin WebChimera shows white rectangle. Since black color is more common for video background I suggest to use it on the plugin preload stage.

**Comment by jaruba** [comment]
shouldn't this be closed? I never get white preload color anymore.

**Comment by RSATom** [comment]
It could be Node-Webkit related - better ask @gyzerok if it solved

**Comment by gyzerok** [comment]
Yeah, suppose it fixed. I've never seen white screen since 0.2.1.

**Comment by RSATom** [comment]
Great, thanks!
