### ISSUE TITLE
Which event is triggered on network error?

### ISSUE THREAD

**Issue by allspace** [RSATom/WebChimera#45]
Steps:
1. Attach function for both MediaPlayerEncounteredError and MediaPlayerStopped
2. Play a network stream
3. Shutdown network
Result:
None of the two events are triggered.
The player keep repeating the last piece of the video

**Comment by RSATom** [comment]
It's definetly libvlc issue. When I shutdown network see nothing even in debug log both plugin and Vlc Player.
