### ISSUE TITLE
More QML - JS Communication Channels

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#47]
Do you think you can make a few more events in JS + functions in QML like "QmlMessage"?

I'm thinking of one for mouse events, another for key press events and one more for button interactions.

All this might be able to be done on the same channel (QmlMessage), but mouse movement for example really crowds the channel and I'm wondering if sending 2 events in the same millisecond to QmlMessage might bug the event.

That way I could leave all events running at the same time and make a lot more comprehensive functions that hook up to each individual player event.

**Comment by RSATom** [comment]
What if I will add another generic (i.e. not specialized to mouse/keyboard events) QmlMessage with extended arguments? Something like QmlMessage2( int type, int arg1, string arg2)? - is it will be enough? Then you could distinguish different message types by first argument.

**Comment by jaruba** [comment]
Doesn't need to have 2 arguments, I can use JSON, just make 2 more exactly like QmlMessage.

**Comment by RSATom** [comment]
QmlMessage2, QmlMessage3 ?

**Comment by jaruba** [comment]
sure

**Comment by RSATom** [comment]
.QmlStringMessage( int type, string message ) and .QmlNumberMessage( int type, int arg1, int arg2 ) JS events added
