### ISSUE TITLE
Next Frame Button

### ISSUE THREAD

**Issue by lshkiller** [RSATom/WebChimera#52]
Hi,

Do you know how I can do a "Next Frame" Button?
For example, I just want to move the 500 milliseconds forward or backward. 
I tryed using .input.time + 500. 
It works when the player is playing but not when the player is paused - when it is paused the time changes but the frames stay.
I want a "Frame by Frame" feeling..
Any suggestions?

Thanks:)

**Comment by jaruba** [comment]
Couldn't we close this, WebChimera Player already has a skip hotkey as described for a long enough time, I already posted the required working QML to make this work and I don't think this should ever be done in WebChimera Plugin, as it makes sense to do it with the JS or QML API, like all the skip/seek features mentioned on [WebChimera Player Hotkeys](http://wiki.webchimera.org/Player_Hotkeys)

**Comment by RSATom** [comment]
Agree, we could close it, Thanks!
