### ISSUE TITLE
Can other QML files be imported in the main QML Source?

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#54]
I've tried the examples mentioned here: http://doc.qt.io/qt-5/qtqml-syntax-imports.html

I even tried importing an entire directory of QML files, I don't get any error from importing, but the screen is white and video doesn't play when I try calling the QML Element from the imported file.

Am I missing something? Or doesn't WebChimera support imported QML Files?

**Comment by RSATom** [comment]
I've found the reason. It's not a bug, It's how Qml works over network. If you need use some folder over network, you have to add file `qmldir` near the .qml files.
http://doc.qt.io/qt-5/qtqml-syntax-directoryimports.html#remotely-located-directories
