### ISSUE TITLE
Focus Problems

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#55]
There are still two focus issues I've stumbled upon while testing.

If you click the video once, the video pauses and the plugin gets focus so you can use the mouse wheel. But if you click the video again, playback starts and the plugin looses focus (mouse wheel and space key to pause don't work anymore). This also happens if the process is repeated, but is fixed after going into fullscreen then minimizing.

Also, when going out of fullscreen, for the first click on the video only the onRelease event is triggered, the onClick and onPressed events are ignored. (I'm still unsure if this is a player or plugin issue, but it seems to be from the plugin)

**Comment by RSATom** [comment]
Thanks, I'll check little later...

**Comment by gyzerok** [comment]
I accept the focus issues, but dont know exactly conditions for testing.

+1 for fixing this.
