### ISSUE TITLE
IE looses plugin focus on click

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#57]
When I try to click a toolbar button or the progress bar in WebChimera Player in IE (tested in IE 10), it looses focus and the ".containsMouse" event (toolbar goes down as if the player does not contain the mouse cursor anymore).

It works to click the player to pause and play but I'm thinking this is because I check for onPressed and onReleased mouse events and normalize them if there are more releases then presses (as a solution for a previous focus problem).

This issue is only in minimized mode, in fullscreen everything works great.

I've noticed this bug a long time ago, just forgot to announce it until now.

**Comment by silid** [comment]
I find if I double click very fast then the toolbar responds - I presume I got focus, then pressed the button.

If I double click slowly the toolbar disappears before I can perform an action.

**Comment by silid** [comment]
I also have to double click the playlist items - though they don't disappear so can be performed slowly. Mouse out seems to lose focus.

Again when fullscreen no problem.

**Comment by jaruba** [comment]
I've played with it a bit more to try to find the real problem behind it. It was easy to come to a conclusion because, as I previously mentioned, the player surface uses onPressed and onReleased events instead of onClicked.

If I click and keep mouse button pressed on player surface, I can see that the onPressed event works and does not loose focus or mouse. But when I release the mouse button, the onRelease event kicks in and looses focus and mouse. This also happens when I click a toolbar button or any other component that uses the onClick event.

So onPressed works, while onReleased and onClick break the focus and mouse.

**Comment by RSATom** [comment]
@jaruba, do you think it's related to plugin, or player only?

**Comment by jaruba** [comment]
It's eighter from the plugin or IE, can't be from the player.

**Comment by RSATom** [comment]
Ok, thanks I'll check

**Comment by RSATom** [comment]
I can confirm bug exist.

**Comment by RSATom** [comment]
It seems it's a bug in Qt - Will try to find solution/workaround...

**Comment by RSATom** [comment]
Bug was in Qt, to fix it Qt rebuild with https://github.com/RSATom/WebChimera/blob/master/patches/qt_wrong_mouse_leave%28issue%2357_fix%29.patch needed.

**Comment by RSATom** [comment]
Patch sent for code review: https://codereview.qt-project.org/#/c/104523/
