### ISSUE TITLE
fbvlc emulation is broken in WebChimera 0.2.2

### ISSUE THREAD

**Issue by paztis** [RSATom/WebChimera#59]
I came from fbvlc 0.1.5. Everything was perfectly working.
I just install WebChimera 0.2.2 and when I use application/x-fb-vlc type, it instantly crashes.

Any idea of the problem ?

**Comment by paztis** [comment]
I'm in windowless mode

**Comment by RSATom** [comment]
Is your OS 32bit or 64bit?
How exactly do you embed plugin to html page?

**Comment by paztis** [comment]
I'm on 64bit.
I use it with object tag : 
<object name="fbvlcPlayer0" id="fbvlcPlayer0" type="application/x-fb-vlc" width="100%" height="100%" style="width: 100%; height: 100%; position: absolute; visibility: visible;">
	<param name="toolbar" value="false">
	<param name="autoplay" value="false">
	<param name="bgcolor" value="#000000">
	<param name="allowfullscreen" value="false">
	<param name="windowless" value="true">
</object>

It crash directly on loading.

**Comment by paztis** [comment]
Sorry I paste my badly my code .
Here is the object

&lt;object name="fbvlcPlayer0" id="fbvlcPlayer0" type="application/x-fb-vlc" width="100%" height="100%" style="width: 100%; height: 100%; position: absolute; visibility: visible;"&gt;
	&lt;param name="toolbar" value="false"&gt;
	&lt;param name="autoplay" value="false"&gt;
	&lt;param name="bgcolor" value="#000000"&gt;
	&lt;param name="allowfullscreen" value="false"&gt;
	&lt;param name="windowless" value="true"&gt;
&lt;/object&gt;

**Comment by RSATom** [comment]
Did you uninstall fbvlc before use WebChimera?

**Comment by paztis** [comment]
No.
Is it a problem ?
The plugin version loaded is 0.2.2 not 0.1.5.

**Comment by RSATom** [comment]
Don't know - just a guess.

**Comment by RSATom** [comment]
Anyway, will check it. Thanks for report!

**Comment by paztis** [comment]
I unistall webchimera and fbvlc the reinstall webchimera.
It's the same. The plugin always crashes.

**Comment by paztis** [comment]
I check the 0.2.0 version and it works.

**Comment by RSATom** [comment]
Thanks for additional info, it will be very helpful.

**Comment by paztis** [comment]
Is it possible to publish a new WebChimera release to have the latest fbvlc working version ?

**Comment by RSATom** [comment]
Yes, I plan to do it this week.

**Comment by paztis** [comment]
Okay.
Thanks

2015-01-20 17:28 GMT+01:00 Sergey Radionov <notifications@github.com>:

**Comment by RSATom** [comment]
ready: https://github.com/RSATom/WebChimera/releases/tag/v.0.2.3

**Comment by YunChengKao** [comment]
I came from fbvlc 0.1.5. Everything was perfectly working. Thanks a lot.
But when I download fbvlc.msi, Symantec software detects it as WS.Reputation.1:
https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99
Is it possible to add fbvlc.msi to the white list of Symantec software to avoid this?
Thanks for your help.

**Comment by RSATom** [comment]
@YunChengKao, `FBVLC` and `WebChimera Plugin` are not supported anymore. And I'm not plan to release any new version, nor fixing any issues.
