### ISSUE TITLE
WebChimera uninstallation

### ISSUE THREAD

**Issue by paztis** [RSATom/WebChimera#60]
How can I uninstall properly WebChimera ?
After running inistallation, plugin is yet available in firefox and IE...

**Comment by RSATom** [comment]
You could uninstall it as other software via "Control Panel"->"Uninstall a program"

**Comment by paztis** [comment]
Yes but after this uninstall, nothing is deleted undex user/---/AppData/Roaming/WebChimera and in register database.

**Comment by RSATom** [comment]
hm... It should, maybe it's a bug. Did you have open any browser window while did uninstall?

**Comment by paztis** [comment]
No. I close all of my browsers.

**Comment by RSATom** [comment]
hm... then it should be a bug, I'll check.

anyway, if you need cleanup after WebChimera uninstallation - you could do 
`regsrv32.exe /u user/---/AppData/Roaming/WebChimera/npWebChimera.dll` and delete WebChimera folder after that

**Comment by paztis** [comment]
It also uninstall ActiveX ?

2015-01-19 11:52 GMT+01:00 Sergey Radionov <notifications@github.com>:

**Comment by RSATom** [comment]
yes

**Comment by paztis** [comment]
OK thanks
Le 19 janv. 2015 11:54, "Sergey Radionov" <notifications@github.com> a
écrit :

**Comment by RSATom** [comment]
Could you please try uninstall WebChimera again (in context of #65)?
