### ISSUE TITLE
Object resize not manage while playing on windowless fbvlc

### ISSUE THREAD

**Issue by paztis** [RSATom/WebChimera#61]
It's the same problem as this old bug: https://code.google.com/p/fbvlc/issues/detail?id=15

If I play a movie in windowless fbvlc, an resite the object tag while playing, the video isn't resized.

**Comment by RSATom** [comment]
Thanks for report!
Btw, why you don't want to use native (i.e. with QML) plugin mode?

**Comment by paztis** [comment]
I've work on a player that wrap over a lot of subplayers (native ghtml, flash, vlc, fbvlc, ...).
I manage an unique user interface in HTML over these players.
QML interface is not compatible with the other players.

**Comment by RSATom** [comment]
But it will have very poor performance, Is it not issue for you?

**Comment by paztis** [comment]
No.

I try the native-scaling parameter, and it's better, but the aspect ratio is not preserved.

**Comment by paztis** [comment]
Is there another way to use the windowed version with html ui over it ?

**Comment by RSATom** [comment]
I'm afraid no. That's the main reason why I started WebChimera - it's allow hardware accelerated video output overlayed by custom controls.

**Comment by RSATom** [comment]
> I try the native-scaling parameter, and it's better, but the aspect ratio is not preserved.
What video source do you use?

**Comment by paztis** [comment]
I try with http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

**Comment by paztis** [comment]
Ok I found trhe problem: It's only when the width of the object tag is the same as the video.
When is set the object tag to 640x500 for exampole, the video fill the square without aspect ratio preserve.
If I set 641x500 or 639x500, the problem is gone. 
It's strange ^^

**Comment by RSATom** [comment]
Yes, it's very strange - but it will be easy to fix, I think :)

**Comment by paztis** [comment]
I found the source of the pb:
in FBVLC_Win.cpp line 115:

if( src_aspect > dst_aspect ) {
                if( w->getWindowWidth() != media_width ) { //don't scale if size equal
                    dst_media_height = static_cast<unsigned>( w->getWindowWidth() / src_aspect + 0.5 );
                }
            }
            else {
                if( w->getWindowHeight() != media_height ) { //don't scale if size equal
                    dst_media_width = static_cast<unsigned>( w->getWindowHeight() * src_aspect + 0.5 );
                }
            }

You may not just test "if( w->getWindowWidth() != media_width )" but "if( w->getWindowWidth() != media_width ||  w->getWindowHeight() != media_height )"

In your case, when the widht is the same, hthe height stays to "dst_media_height " (the window height) instead of "media_height". So the video is stretched to the window without aspect radio preserve.



It's the same for line 121.

**Comment by paztis** [comment]
or something like this:

if( w->getWindowWidth() != media_width ) { //don't scale if size equal
    dst_media_height = static_cast<unsigned>( w->getWindowWidth() / src_aspect + 0.5 );
}
else {
    dst_media_height  = media_height;
}

It's better and less resources consumer

**Comment by RSATom** [comment]
You are right, second variant is better. Used it.

**Comment by RSATom** [comment]
But If you will need resize plugin window with `native-scaling=false` - I'm afraid then you have to use trick with:
1) save position;
2) stop playing;
3) resize window;
4) start playing;
5) restore position;

as it was there:
https://github.com/RSATom/fbvlc/blob/5e2ad1925b41d595a4c9ab70e1e060c20cbec59f/FBVLC.htm#L90

**Comment by paztis** [comment]
Thanks.

I need it because off  my fullscreen mode.
I use HTML fullscreen API. So I apply fullscreen to the parent of the fbvlc plugin.
So fbvlc is implicitely resized.
It's not too long to stop / reload the video ?

**Comment by RSATom** [comment]
it's pretty quick but still visible to user. You should try it yourself.
