### ISSUE TITLE
HLS and TS files length and time attributes always to 0

### ISSUE THREAD

**Issue by paztis** [RSATom/WebChimera#62]
With fbvlc, when I read HSL files (not streams) or TS files, the duration (lenght) and the current time (time) attributes are always to 0. 
But it's not live streams. It's file playing.
The input.position attribute seems to be ok.

**Comment by jaruba** [comment]
This seems related to this bug report:

https://github.com/RSATom/WebChimera/issues/58

**Comment by RSATom** [comment]
It's very possible libvlc issue. I'll check, thanks!

**Comment by RSATom** [comment]
It's libvlc issue, if you open same file with VLC Player you don't see length and time there too.
