### ISSUE TITLE
fbvlc crashes at the end of a HLS file

### ISSUE THREAD

**Issue by paztis** [RSATom/WebChimera#63]
I try to read the file http://playertest.longtailvideo.com/adaptive/bipbop/bipbop.m3u8 with fbvlc.
A the end of the file (1mn39), it takes a very long time to set state to IDLE.
Then, when I try to load another video, it crashes.

**Comment by RSATom** [comment]
Thanks for report.

**Comment by RSATom** [comment]
It's a bug in libvlc, ticket created: https://trac.videolan.org/vlc/ticket/13801
