### ISSUE TITLE
Subtitles correct mime ?

### ISSUE THREAD

**Issue by zxvfbg** [RSATom/WebChimera#64]
Hello guys.

First of all great job ! :)

I am trying to load srt subtitles with webchimera, but i want to know what mimetype the player expects ? By default web servers are returning application/octet-stream for srt and sub files.
I try with both application/octet-stream and also text/plain in Windows-1251 encoding and also in UTF-8, but i was unable to load subtitles. I also see that your demo http://www.webchimera.org/demos/external_subtitle with external subtitles doesn't work too.

Is there some optional setting ?

Thanks

**Comment by RSATom** [comment]
I think @Jaruba will answer better this question - let's wait him.

**Comment by zxvfbg** [comment]
I have found the problem.

These two lines:

if (message.startsWith("[start-subtitle]")) playSubtitles(message.replace("[start-subtitle]", ""));
	
if (message.startsWith("[load-m3u]")) playM3U(message.replace("[load-m3u]",""));

in functions.js inside function onMessage must be before:

var jsonMessage = JSON.parse(message);

Actually after parsing of the message you can't use startsWith method because you have object :)

**Comment by jaruba** [comment]
Sorry for the late response, I was awake all night..

The lines you found can't be the problem because ```var jsonMessage = JSON.parse(message);``` converts ```message``` from an object to an array in the ```jsonMessage``` variable, while:

```
if (message.startsWith("[start-subtitle]")) playSubtitles(message.replace("[start-subtitle]", ""));

if (message.startsWith("[load-m3u]")) playM3U(message.replace("[load-m3u]",""));
```

both check ```message``` (which is unconverted), not ```jsonMessage``` (the converted array)

With that said, the external subtitles demo just doesn't work on the site (I've been experimenting with adding a skinning function in JS and did some tests on the site's player, didn't know I managed to break the demo), while the latest Developer Kit Release (downloadable from: http://www.webchimera.org/download , can also be found online at: http://jaruba.github.io/WebChimeraPlayer/ ) works fine with external subtitles.

When I tested running ```.srt``` files in the player, I used a ```text/plain``` file (although the file header shouldn't matter at all), encoded in ```UTF-8```, could you please upload your ```.srt``` file somewhere and link it here so I can also test the player with it? :)

**Comment by jaruba** [comment]
Fixed on the site too ( http://www.webchimera.org/demos/external_subtitle ), the JavaScript Logic broke with an error when ```message``` was not a JSON data object (like when adding subtitles).

I now added a prototype function to check if the variable is JSON or not before using ```JSON.parse(message)```

**Comment by RSATom** [comment]
@jaruba, Thanks!

**Comment by zxvfbg** [comment]
Guys is there some minimal requirements for that plugin ? Like video memory or ram memory ?

I try to run it today on machine with 2gb ram and mobile radeon graphic adapter and doesn't work ?

Anything special ?

**Comment by jaruba** [comment]
What OS?

**Comment by zxvfbg** [comment]
Windows 7 - whole Chrome crashes after plugin load

**Comment by jaruba** [comment]
Download and Install: https://technet.microsoft.com/en-us/sysinternals/bb896647.aspx

And print the error log from the player when it crashes here so that RSATom can debug.

**Comment by zxvfbg** [comment]
00000001	0.00000000	[3632] Chimera_Win::StaticInitialize()	
00000002	0.00934627	[3632] Chimera_Win::Chimera_Win()	
00000003	1.68189788	[3632] QQmlExpression: Expression http://xxx/share/player/player//themes/sleek/components/PlaylistMenuScroll.qml:32:11 depends on non-NOTIFYable properties:	
00000004	1.68196046	[3632]     QmlVlcPlaylist::itemCount	
00000005	1.68281460	[3632] QQmlExpression: Expression http://xxx/share/player/player//themes/sleek/main.qml:245:15 depends on non-NOTIFYable properties:	
00000006	1.68286490	[3632]     QmlVlcPlaylist::itemCount	
00000007	1.68351340	[3632] QQmlExpression: Expression http://xxx/share/player/player//themes/sleek/components/VolumeHeatGraphics.qml:24:11 depends on non-NOTIFYable properties:	
00000008	1.68353653	[3632]     QmlVlcSurfacePlayerProxy::volume	
00000009	1.68371761	[3632] QQmlExpression: Expression http://xxx/share/player/player//themes/sleek/main.qml:184:12 depends on non-NOTIFYable properties:	
00000010	1.68376434	[3632]     QmlVlcAudio::mute	
00000011	1.68400431	[3632] QQmlExpression: Expression http://xxx/share/player/player//themes/sleek/main.qml:171:15 depends on non-NOTIFYable properties:	
00000012	1.68455136	[3632]     QmlVlcPlaylist::itemCount	
00000013	1.68459308	[3632] QQmlExpression: Expression http://xxx/share/player/player//themes/sleek/main.qml:140:15 depends on non-NOTIFYable properties:	
00000014	1.68464243	[3632]     QmlVlcPlaylist::itemCount	
00000015	1.68521893	[3632] QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0	
00000016	1.68532407	[3632] QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0	
00000017	1.68555450	[3632] QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0	
00000018	1.68565869	[3632] QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0	
00000019	2.23875308	[3632] http://xxx/share/player/player//core/functions.js:274: JSON.parse: Parse error	
00000020	2.27786279	[3632] QImage::pixel: coordinate (0,1) out of range	
00000021	2.27793479	[3632] QImage::pixel: coordinate (1,0) out of range	
00000022	2.33258557	[3632] D3D11: Removing Device.	
00000023	2.33278251	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000024	2.33278251	[3632] 	
00000025	2.33348584	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000026	2.33348584	[3632] 	
00000027	2.35511208	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000028	2.35511208	[3632] 	
00000029	2.35722756	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000030	2.35722756	[3632] 	
00000031	2.35965657	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000032	2.35965657	[3632] 	
00000033	2.36102653	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000034	2.36102653	[3632] 	
00000035	2.36429262	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000036	2.36429262	[3632] 	
00000037	2.36759162	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000038	2.36759162	[3632] 	
00000039	2.36940718	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000040	2.36940718	[3632] 	
00000041	2.37109518	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000042	2.37109518	[3632] 	
00000043	2.37310624	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000044	2.37310624	[3632] 	
00000045	2.37476254	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000046	2.37476254	[3632] 	
00000047	2.37812018	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000048	2.37812018	[3632] 	
00000049	2.54686809	[3632] QOpenGLShaderProgram: could not create shader program	
00000050	2.54696774	[3632] QOpenGLShader: could not create shader	
00000051	2.54703665	[3632] QOpenGLShader: could not create shader	
00000052	2.54708457	[3632] shader compilation failed: 	
00000053	2.54708457	[3632] ""	
00000054	2.54713225	[3632] QOpenGLShaderProgram::uniformLocation( qt_Matrix ): shader program is not linked	
00000055	2.54717708	[3632] QOpenGLShaderProgram::uniformLocation( opacity ): shader program is not linked	
00000056	2.54743552	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000057	2.54743552	[3632] 	
00000058	2.55262709	[3632] QOpenGLShaderProgram: could not create shader program	
00000059	2.55269647	[3632] QOpenGLShader: could not create shader	
00000060	2.55275893	[3632] QOpenGLShader: could not create shader	
00000061	2.55280495	[3632] shader compilation failed: 	
00000062	2.55280495	[3632] ""	
00000063	2.55285215	[3632] QOpenGLShaderProgram::uniformLocation( qt_Matrix ): shader program is not linked	
00000064	2.55289698	[3632] QOpenGLShaderProgram::uniformLocation( opacity ): shader program is not linked	
00000065	2.55314112	[3632] QWindowsEGLContext::swapBuffers: eglError: 12302, this: 0x4f7bdd8 	
00000066	2.55314112	[3632] 	
00000067	2.55762196	[3632] QOpenGLShaderProgram: could not create shader program	
00000068	2.55769038	[3632] QOpenGLShader: could not create shader	
00000069	2.55775237	[3632] QOpenGLShader: could not create shader	
00000070	2.55779862	[3632] shader compilation failed: 	
00000071	2.55779862	[3632] ""

**Comment by zxvfbg** [comment]
Now i see that OpenGL cannot be initializied, but in that case i think that would be normal if there is some fallback or message ?

Problem is described here: http://qt-project.org/forums/viewthread/52224

**Comment by RSATom** [comment]
Could you please try WebChimera plugin v.0.2.0 there? - It's possible I use wrong Qt build in newer versions.

**Comment by zxvfbg** [comment]
I have tested with that https://github.com/RSATom/WebChimera/releases/download/v0.2.0/WebChimera_0.2.0_vlc_2.1.5.msi

I have only white screen and nothing inside DebugView except that is loading js files.

**Comment by RSATom** [comment]
I think it's something wrong with video drivers then. Could you try reinstall video drivers?

**Comment by jaruba** [comment]
The white screen might also be because the newer versions of WebChimera Player use QtGraphicalEffects and API functions that WebChimera Plugin v0.2.0 does not support yet.

**Comment by zxvfbg** [comment]
Nope actually is playing because i hearing a sound. RSATom i have installed last drivers from intel.com for that adapter.

**Comment by jaruba** [comment]
if you hear sound, then webchimera plugin is working correctly, and the QML gave an error so it shows the white screen. Try downloading ( https://github.com/jaruba/WebChimeraPlayer/releases ) an older version (v0.9 maybe) of WebChimera Player and see if it works.

**Comment by RSATom** [comment]
@zxvfbg, could you try demos on http://rsatom.github.io/WebChimera then? - They are much simpler internally.

**Comment by RSATom** [comment]
@zxvfbg, hm, Intel? What exactly video do you have there?

**Comment by zxvfbg** [comment]
Mobile Intel (R) 4 Series Express Chipset Family

That is what i recieve from DebugViewer with 0.2.3

00000001	0.00000000	[3088] Chimera_Win::Chimera_Win()	
00000002	0.02000040	[3088] void *__thiscall QWindowsEGLStaticContext::createWindowSurface(void *,void *): Could not create the EGL window surface: 0x300e	
00000003	0.02000040	[3088] 	
00000004	0.02027983	[3088] QWindowsEGLContext::makeCurrent: eglError: 3009, this: 0x8671280 	
00000005	0.02027983	[3088] 	
00000006	0.11694133	[3088] void *__thiscall QWindowsEGLStaticContext::createWindowSurface(void *,void *): Could not create the EGL window surface: 0x300e	
00000007	0.11694133	[3088] 	
00000008	0.11700111	[3088] QWindowsEGLContext::makeCurrent: eglError: 3009, this: 0x8671280 	
00000009	0.11700111	[3088] 	
00000010	1.08326912	[3088] QQmlExpression: Expression http://www.webchimera.org/player/themes/sleek/components/PlaylistMenuScroll.qml:32:11 depends on non-NOTIFYable properties:	
00000011	1.08332622	[3088]     QmlVlcPlaylist::itemCount	
00000012	1.08413875	[3088] QQmlExpression: Expression http://www.webchimera.org/player/themes/sleek/main.qml:243:15 depends on non-NOTIFYable properties:	
00000013	1.08418894	[3088]     QmlVlcPlaylist::itemCount	
00000014	1.08472562	[3088] QQmlExpression: Expression http://www.webchimera.org/player/themes/sleek/components/VolumeHeatGraphics.qml:24:11 depends on non-NOTIFYable properties:	
00000015	1.08477497	[3088]     QmlVlcSurfacePlayerProxy::volume	
00000016	1.08508480	[3088] QQmlExpression: Expression http://www.webchimera.org/player/themes/sleek/main.qml:169:15 depends on non-NOTIFYable properties:	
00000017	1.08513963	[3088]     QmlVlcPlaylist::itemCount	
00000018	1.08557892	[3088] QQmlExpression: Expression http://www.webchimera.org/player/themes/sleek/main.qml:138:15 depends on non-NOTIFYable properties:	
00000019	1.08562875	[3088]     QmlVlcPlaylist::itemCount	
00000020	1.08613276	[3088] QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0	
00000021	1.08623564	[3088] QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0	
00000022	1.08646154	[3088] QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0	
00000023	1.08656621	[3088] QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0	
00000024	1.13914597	[3088] QQmlExpression: Expression http://www.webchimera.org/player/themes/sleek/main.qml:182:12 depends on non-NOTIFYable properties:	
00000025	1.13984740	[3088]     QmlVlcAudio::mute	
00000026	1.14434505	[3088] void *__thiscall QWindowsEGLStaticContext::createWindowSurface(void *,void *): Could not create the EGL window surface: 0x300e	
00000027	1.14434505	[3088] 	
00000028	1.14436996	[3088] QWindowsEGLContext::makeCurrent: eglError: 3009, this: 0x8671280 	
00000029	1.14436996	[3088] 	
00000030	1.23205030	[3088] void *__thiscall QWindowsEGLStaticContext::createWindowSurface(void *,void *): Could not create the EGL window surface: 0x300e	
00000031	1.23205030	[3088] 	
00000032	1.23209286	[3088] QWindowsEGLContext::makeCurrent: eglError: 3009, this: 0x8671280 	
00000033	1.23209286	[3088] 	
00000034	1.23798895	[3088] void *__thiscall QWindowsEGLStaticContext::createWindowSurface(void *,void *): Could not create the EGL window surface: 0x300e	
00000035	1.23798895	[3088] 	
00000036	1.23802793	[3088] QWindowsEGLContext::makeCurrent: eglError: 3009, this: 0x8671280 	
00000037	1.23802793	[3088] 	
00000038	2.66021109	[3088] void *__thiscall QWindowsEGLStaticContext::createWindowSurface(void *,void *): Could not create the EGL window surface: 0x300e	
00000039	2.66021109	[3088] 	
00000040	2.66121602	[3088] QWindowsEGLContext::makeCurrent: eglError: 3009, this: 0x8671280 	
00000041	2.66121602	[3088] 	
00000042	3.31893396	[3088] main vout display error: Failed to change zoom	
00000043	3.31905746	[3088] main vout display error: Failed to set on top	
00000044	3.31916547	[3088] main vout display error: Failed to change source AR	
00000045	3.33595943	[3088] void *__thiscall QWindowsEGLStaticContext::createWindowSurface(void *,void *): Could not create the EGL window surface: 0x300e

**Comment by RSATom** [comment]
Looks the same, try please with v0.2.0 with http://rsatom.github.io/WebChimera

**Comment by zxvfbg** [comment]
Still the same ... may be video adapter does not support OpenGL ?

**Comment by RSATom** [comment]
Something in logs?
v0.2.0 uses DirectX, not OpenGL, but v0.2.2 could use both (not sure 100% this time)...

**Comment by zxvfbg** [comment]
Nothing ... just the previous error which i paste

**Comment by RSATom** [comment]
Ok, thanks, I'll try find something on my side...

**Comment by RSATom** [comment]
Checked Qt build options for v0.2.3 - it's ok and uses Angle lib (it's wrapper for use DirectX) - same as in v0.2.0 (i.e. OpenGL not used on Windows at all in any versions).
Don't sure how I can solve this problem without access to such hardware.... Anyway, please create separate issue - I'll try investigate it later.

**Comment by smqtai22** [comment]
http://textuploader.com/nejz same problem here

**Comment by RSATom** [comment]
It seems we found the solution with help of @smqtai22. The reason of problem is old GMA video drivers has broken DirectX 11  support.
To avoid the problem, it's possible force use DirectX 9 - to achieve this one will need set `QT_ANGLE_PLATFORM` environment variable to `d3d9`, for example via "My Computer -> Properties -> Advanced System Settings -> Advanced -> Environment Variables"
