### ISSUE TITLE
WebChimera 0.2.3 install

### ISSUE THREAD

**Issue by paztis** [RSATom/WebChimera#65]
Hello,
I try to install 0.2.3 (WebChimera_0.2.3_vlc_2.1.5.msi), but the installer ask me the nework location of WebChimera_0.2.2_vlc_2.1.5.msi, then WebChimera_0.2.0_vlc_2.1.5.msi.

Is it necessary to have older version installers ?

**Comment by RSATom** [comment]
I think it's needed for uninstall - maybe you windows installer database corrupted or something similar. But I don't sure. I never met this.

**Comment by RSATom** [comment]
btw, #60 could be the same problem of corrupted installer database...

**Comment by paztis** [comment]
OK I've download them and now it works

**Comment by paztis** [comment]
I check it.
It works now.
Seems to be a pb in older versions uninstall.

Thanks
