### ISSUE TITLE
Clear subtitles text

### ISSUE THREAD

**Issue by zxvfbg** [RSATom/WebChimera#67]
I think that is good to have function to clear currently loaded subtitles file.

In addition i wrote this:

in functions.js after line 363:

if (message.startsWith("[clear-subtitle]")) clearSubtitles();

Function itself in functions.js

function clearSubtitles() {
	
	subtitlebox.changeText = "";
	
	currentSubtitle = -2;
	
	subtitles = [];
	
}

Modification in webchimera.js:

wjs.init.prototype.clearSubtitle = function() {
	
	this.videoelem.emitJsMessage("[clear-subtitle]");

};

**Comment by RSATom** [comment]
It's WebChimera Player issue, better create it there: https://github.com/jaruba/WebChimeraPlayer/issues

**Comment by jaruba** [comment]
I added it to the repo: https://github.com/jaruba/WebChimeraPlayer/commit/4f2ef3b1c28f1f2222494a50695cca8ac0869dd6

**Comment by RSATom** [comment]
@jaruba, Thanks!
