### ISSUE TITLE
qmldir request

### ISSUE THREAD

**Issue by zxvfbg** [RSATom/WebChimera#69]
Hello.

After some debugging with Jaruba we have seen a strange request which is not maded from WebChimera Player and we think that is maded from WebChimera plugin because in WebChimera Player there is no qmldir variable. Here is what happens at plugin loads:

2015/02/03 18:44:32 [error] 24848#0: *527770 open() "/www/share/player/player/themes/sleek/qmldir" failed (2: No such file or directory)

2015/02/03 18:44:33 [error] 24849#0: *527792 open() "/www/share/player/player/themes/sleek/components/qmldir" failed (2: No such file or directory)

May be its some variable in the plugin ?

**Comment by RSATom** [comment]
it's qml service file. It's normal behaviour qml engine try open this file on qml load.
http://doc.qt.io/qt-5/qtqml-modules-qmldir.html

**Comment by RSATom** [comment]
And this file is optional.

**Comment by gyzerok** [comment]
@zxvfbg you can just add empty qmldir file. It works.

**Comment by RSATom** [comment]
Why it's necessary? missing `qmldir` is not error.

**Comment by gyzerok** [comment]
@RSATom when i've tried to use WC without this file on OS X it havent work

**Comment by RSATom** [comment]
even if you use only one .qml file?

**Comment by gyzerok** [comment]
@RSATom yep

**Comment by RSATom** [comment]
it's strange... ok, understand, thanks!

**Comment by RSATom** [comment]
I thought about it little more, I'm not use any `qmldir` on http://rsatom.github.io/WebChimera/ demos - and them works fine on Mac OS X. So in your case @gyzerok there was some another reason of problems.

Anyway, I think this question could be closed as pretty well answered.
