### ISSUE TITLE
Bug with MediaPlayerTimeChanged argument

### ISSUE THREAD

**Issue by gyzerok** [RSATom/WebChimera#70]
There is a bug with an argument that receives MediaPlayerTimeChanged callback in QML and JS API. Documentation says its seconds, but originally its milliseconds.

**Comment by RSATom** [comment]
Then it's mistake in wiki.

**Comment by gyzerok** [comment]
Not just in wiki. The name of an argument is seconds in the code too.

**Comment by RSATom** [comment]
ok, understand, will fix it too. Thanks!
