### ISSUE TITLE
plugin.href() ?

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#71]
Is it possible to have something in the API that opens links in the default browser (it would be great if it could actually be called as "new tab", but I doubt that's possible).

The reason I ask is because the main problem of the plugin is that the browser can't capture user interaction (like clicks) from QML and I've made a context menu ( has more actions during playback, demo: http://www.webchimera.org/demos/default_skin ), but the "About Webchimera" button will trigger a "Pop-up Block" in Chrome because it can't detect the visitor's click.

**Comment by RSATom** [comment]
This question needs some investigations. I'll look.

**Comment by jaruba** [comment]
Thinking about it, something like ``plugin.href()`` could be used for spamming, maybe a ``plugin.home()`` would be better, to just open the official site.

**Comment by RSATom** [comment]
good idea
