### ISSUE TITLE
.playlist.advanceItem(i, count)

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#72]
If the playlist item I am moving is the ".playlist.currentItem", then "currentItem" also changes to the new position, but if I'm moving a different item over the "currentItem", then "currentItem" does not change, and the playlist says it's playing a different mrl (the new one), when it's actually playing the item that was moved. I think in this case, "currentItem" should also move to the new position of the playing video.

**Comment by RSATom** [comment]
Thank you for report!

**Comment by jaruba** [comment]
I found out more about this bug. It seems that it doesn't work only when "count" is negative and the target item is "currentItem". If "count" is positive, "currentItem" changes as it should.

**Comment by jaruba** [comment]
I found one more bug with ".advanceItem()". Presuming there are 5 elements in a list, the forth one is ".currentItem", if I move the third one to the second position (using "vlcPlayer.playlist.advanceItem(2,-1)"), then the fifth item is made ".currentItem". In this case, ".currentItem" should not change position at all.

**Comment by RSATom** [comment]
I hope it fixed. Thanks!

**Comment by jaruba** [comment]
Have not met any more problems with ``.advanceItem()`` in QML API, but in the JS API it's not doing what it's supposed to. Is it possible you fixed the last issues only on QML side?

**Comment by RSATom** [comment]
it's very strange since implementations are identical:
QML: https://github.com/RSATom/QmlVlc/blob/master/QmlVlcPlaylist.cpp#L187
````
void QmlVlcPlaylist::advanceItem( unsigned idx, int count )
{
    player().advance_item( idx, count );
}
````
JS: https://github.com/RSATom/WebChimera/blob/master/src/ChimeraAPI.cpp#L476

````
void JSPlaylistAPI::advanceItem( unsigned idx, int count )
{
    ChimeraPtr plg = getPlugin();
    vlc_player& p = plg->get_player();
    p.advance_item( idx, count );
}
````

**Comment by RSATom** [comment]
what exactly problem did you get?

**Comment by jaruba** [comment]
I was trying to make this enhancement: https://github.com/jaruba/WebChimeraPlayer/issues/5

But as changing the MRL of the currently playing playlist item is not possible with the Plugin API, I had to add a new playlist item, then use ``.advanceItem()`` to move the new (last) item instead of the one that need to be replaced, then remove the old one.. this would keep the playlist intact and also give me the chance to autoplay the new mrl if the current playlist item MRL was changed.

After a lot of testing, I finally realised that ``.advanceItem()`` wasn't doing what it was supposed to in the JS API, then when using ``.emitJsMessage()`` and doing the exact same thing with ``.advanceItem()`` on the QML side, everything worked correctly and the playlist items wore replaced as they should be.

**Comment by RSATom** [comment]
Intresting, Ok, I'll check.

**Comment by RSATom** [comment]
@jaruba, does JS `.advanceItem` not works at all or works wrong?

**Comment by jaruba** [comment]
Works wrong, changes the wrong items and/or puts them in wrong position.

**Comment by RSATom** [comment]
Can't catch it. 
Tested on http://www.webchimera.org/demos/m3u_playlist with

    wjs("#webchimera").plugin.playlist.advanceItem(0, 1);
    wjs("#webchimera").plugin.playlist.items[0].mrl;

it looks works fine. Maybe you used something more complex? Can you give some example?

**Comment by jaruba** [comment]
Try this scenarios:

3 item playlist, add 1 more playlist item, then with first item playing do:

    wjs("#webchimera").plugin.playlist.advanceItem(3, 0);

also try in same scenario, second item playing, do:

    wjs("#webchimera").plugin.playlist.advanceItem(3, 1);

**Comment by jaruba** [comment]
I changed the code above a bit, I added the "[refresh-playlist]" to also visually refresh the playlist so you can see the changes.

**Comment by RSATom** [comment]
How exactly I should add fourth item?

**Comment by jaruba** [comment]
By using [.addPlaylist()](http://wiki.webchimera.org/.addPlaylist()http://wiki.webchimera.org/.addPlaylist()) again. it can be with the same mrl, doesn't matter.

Or just add 4 items at the start. Don't think adding it later will make any difference. I just said explained how I encountered the bug.

**Comment by RSATom** [comment]
Understand, thanks. Will try to reproduce.

**Comment by RSATom** [comment]
Can't reproduce :(
I should ask just to be sure: do you know playlist indexes start from zero? i.e. `advanceItem(3, -3)` should make fourth item first.

**Comment by jaruba** [comment]
I'll try to reproduce this again and make a snippet of some kind to demonstrate it.

**Comment by RSATom** [comment]
ok, thanks.

**Comment by jaruba** [comment]
I found the issue. :)

It was not ``.playlist.advanceItem()`` that was causing it, it was ``.playlist.removeItem()`` as it was also part of the logic.

    // create player
    wjs("#player_wrapper").addPlayer({ autoplay: 1 });
    
    // add the playlist items to the player
    wjs().addPlaylist("http://archive.org/download/CrayonDragonAnAnimatedShortFilmByTonikoPantoja/Crayon%20Dragon%20-%20An%20animated%20short%20film%20by%20Toniko%20Pantoja.mp4");
    
    wjs().addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");
    
    wjs().addPlaylist("http://archive.org/download/CartoonClassics/Mel-O-Toons__Peter_and_the_Wolf.mp4");
    
    // change to second playlist item after 1 second
    setTimeout(function() {
        wjs().next();
    },1000)
    
    setTimeout(function() {
        // open playlist menu
        wjs().togglePlaylist();
        setTimeout(function() {
            // remove second item (currently playing item)
            wjs().plugin.playlist.removeItem(1);
            // refresh playlist visually
            wjs().plugin.emitJsMessage("[refresh-playlist]");
        },2000);
    },5000);

try this code in the JS textbox on: http://editor.webchimera.org/default_skin

The problem is that if the current playlist item is removed, the video should stop playing that item and start playing the next item.

Currently, it removed the currently playing item, sets the next item as current item but does not start playing it. So the wrong item is selected in the playlist.

**Comment by RSATom** [comment]
Good find. Thanks. Will fix it soon.

**Comment by RSATom** [comment]
> Currently, it removed the currently playing item, sets the next item as current item but does not start playing it. So the wrong item is selected in the playlist.

This little bit not clear to me. Why fact it not start playing next item lead to wrong selection?

**Comment by jaruba** [comment]
Don't know, but the playlist menu selects the playlist item that is equal to ``.currentItem``.

So ``.currentItem`` remains 1 after playlist item 1 (which was selected) is removed. (in a 3 playlist items scenario)

Also, if you remove the third ``.addPlaylist()`` from the example code I gave, you will also see that if there are only 2 items in the playlist, second is selected and removed, first will become selected while the removed item is still playing.

**Comment by RSATom** [comment]
It seems I understand what's wrong - it's *not* stop playing item after remove.

**Comment by RSATom** [comment]
Should I check if current item is playing and if yes start playing new selected item, or just stop playing will be enough?

**Comment by jaruba** [comment]
I guess that if the item being removed is the current playing item, then if it is the last item in the playlist.. it should stop completely as there are no next items, otherwise, it should start playing the next item.
