### ISSUE TITLE
Installations problems with Google Chrome

### ISSUE THREAD

**Issue by smolleyes** [RSATom/WebChimera#73]
hi

just discovered your peoject wich seems great !
BUT

can t find any infos or packages to use it on linux first (deb or ppa planned?)

and on windows i donwload the 0.2.3_vlc_2.5.1.msi

it start and just disappear... nothing is installed (windows seven pro x64)

an idear?

thanks

edit: works fine on osX :)

it think having this plugin working and easily embeadable in node-webkit or nwjs apps on all 3 platforms could be a GREAT GREAT GREAT thing since it s the biggest problems of node-webkit for me (codecs...)

thanks !

**Comment by jaruba** [comment]
About Windows, do you have the folder: "%AppData%\WebChimera\"  after trying to install?

**Comment by smolleyes** [comment]
hi

yup i have it in the Roaming dir

**Comment by smolleyes** [comment]
and can see it the program list too but not in chrome://plugins

**Comment by jaruba** [comment]
What Chrome version are you using? Is it by any chance Chrome Canary? (the one with the golden icon)

**Comment by smolleyes** [comment]
no i have Version 42.0.2298.0 beta-m

can try stable version

**Comment by jaruba** [comment]
On the page where you tried to use it, did you enable plugins site wide?

To do this, on the page where you have WebChimera content, there should be another icon in the upper right side of the screen (left of the star icon), click it, then select "Allways allow ..." and refresh the page.

**Comment by smolleyes** [comment]
hummm chrome 42 seems stable now i reinstalled it and have 

Version 42.0.2298.0 m

now... and no webchimera in chrome://plugins

**Comment by smolleyes** [comment]
it do not ask authoriation when i try the demos page, on oSx i can see the plugin navigator.plugins or chrome://plugins not on windows

js error from demos pages

Uncaught TypeError: Cannot read property 'name' of undefined

**Comment by jaruba** [comment]
What demo did you try? Also, was it from the website or the player developer kit?

**Comment by smolleyes** [comment]
i just try the http://www.webchimera.org/demos/mouse_events

:)

**Comment by smolleyes** [comment]
do you know where does chrome load the plugin from normally ?

**Comment by jaruba** [comment]
It should be in "chrome://plugins/" where you looked. As of where it loads the plugins on the disk, this is an NPAPI plugin so it can be anywhere.

Did you try in any other browser? Like FireFox, Opera?

**Comment by smolleyes** [comment]
strange :/

i ll try to download firefox, brb

**Comment by jaruba** [comment]
I have Chrome v40.0.2214.111 m and the plugin works fine. Maybe they changed something in v42.x

**Comment by smolleyes** [comment]
question... if i want to use this player  in node-webkit (think you know it) users have to install this plugin or the webshimera player is sufficient ?

**Comment by smolleyes** [comment]
humm it works in firefox... just ask to enable it

**Comment by jaruba** [comment]
Also, I did an update check for Chrome just now and it says that v40.0.2214.111 m is the latest version. so how can v42.x be a stable version? :/

Yeah, people need to install WebChimera Plugin too, the Player is the User Interface and an Extended JS API for the plugin.

**Comment by smolleyes** [comment]
ok thanks 

hummm, strange i ll remove chrome and redownload it

**Comment by smolleyes** [comment]
ok all right

Version 40.0.2214.111 m

and i have the webchimera plugin in chrome:// plugins now... strange

i ll ask about linux version in another topic, thanks for your help

do you think it s possible to embed all this files in a node-webkit app (without having to use the msi installer?)

**Comment by jaruba** [comment]
I'm not too accustomed with node-webkit (not enough time on my hands) @zxvfbg might be able to help you with this though.

**Comment by smolleyes** [comment]
ok thanks a lot jaruba :)

**Comment by jaruba** [comment]
no problem, sorry if you see debug text on the demos of the site, I'm testing some new features now on the player site wide.

**Comment by smolleyes** [comment]
np :)

i ll make some test with node-webkit, for the moment  use a live transcoder i made with ffmpeg it works very well but need to much cpu :/ ...dream to replace it wih this plugin !

**Comment by zxvfbg** [comment]
Hey smolleyes :) From my tries i cannot embed webchimera in nodewebkit. Actually i can load it like plugin but it doesnt work which means that the msi package writes some registry or something like that. If somebody haves an idea why isnt working as standalone will be great :)

**Comment by smolleyes** [comment]
Hi zxvfbg :)

I have it working in my node webkit app (not standalone yeah...) just don t understand how To load the qml files ... And really need a linux version 

Once we have it ans it s standalone it will be a biiiiiiig progress for multimédia apps written with node webkit :)

**Comment by RSATom** [comment]
http://isoplex.isohunt.to/ uses WebChimera as player internally.
It based on Node-Webkit.
It don't require install WebChimera ( https://github.com/nwjs/nw.js/wiki/Third-party-browser-plugins#location-of-plugins ).

But you should know, current release of WebChimera has issues with load local .qml under node-webkit. It's already fixed and will be available in the next WebChimera release ( https://github.com/RSATom/WebChimera/commit/50474d12a8bc1632b8da3d185512ee495749a2e4 ) - but you will have to use `app://` protocol: https://github.com/nwjs/nw.js/wiki/App-protocol

**Comment by smolleyes** [comment]
Hi 

Thanks for your reply :) 

I LL try this asap !

**Comment by smolleyes** [comment]
Ola

It s OK on windows embedding works and qml loading too with app:// protocol ! I LL learn qml while waiting for linux release :)

Thanks !

**Comment by smolleyes** [comment]
Zxvfgb what s nor working for you ?

I copied all files of appData/webchimera/... In a plugins dir where my package.json is and everything works

**Comment by zxvfbg** [comment]
I am working with an older version of nodewebkit may be that is the reason. When i try your method there is only blackscreen inside nodwebkit. With which version of nodewebkit are you working ?

**Comment by jaruba** [comment]
If you get a black screen, use DebugView ( https://technet.microsoft.com/en-us/library/bb896647.aspx ) and check the error log. Might be just a qml error.

**Comment by RSATom** [comment]
I think now it could be closed...

**Comment by naveen1988** [comment]
My web application uses VLC player for rtsp video streaming, After installing chrome 45 canary, it stops all NPAPI plugin and now i am not able to stream a video in Chrome. Can you suggest me how can i overcome this problem using Webchimera
Thanks in advance

**Comment by RSATom** [comment]
@naveen1988, there are no way to use `WebChimera` with Chrome now, since it's based on NPAPI too.

**Comment by RSATom** [comment]
@naveen1988, all I can suggest to you at the moment - consider create desktop app for your site with `NW.js`/`Electron` + [`WebChimera.js`](https://github.com/RSATom/WebChimera.js)
