### ISSUE TITLE
Subtitle / Audio Track correction

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#77]
There is mentioned here http://www.shortcutworld.com/en/win/VLC-Media-Player.html that vlc uses "G / H" to "Decrease / increase subtitle delay" and "J / K" to "Decrease / increase audio delay".

I would like to add this feature to the player too but I can only add or subtract seconds from the externally loaded subtitles because their loaded in QML, but for those that I enable with ".subtitle" or ".audio", I can't modify the time when subtitles are shown or audio is played.

**Comment by RSATom** [comment]
it's pretty possible. I'll add it. Thanks!
