### ISSUE TITLE
".time" is not writable in avi

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#80]
If I do ```vlcPlayer.time = 60000``` it won't go to minute 1, it just jumps 10 seconds in the future regardless of the number I set.

**Comment by RSATom** [comment]
Does it happens on any media source or only some of them?

**Comment by jaruba** [comment]
Apparently it happens only to the videos that have this issue: https://github.com/RSATom/WebChimera/issues/76

I guess they are somehow related..

**Comment by RSATom** [comment]
Then I'm afraid It's libvlc issue... Btw, did you try same case in Vlc player? How is it behave in this situation?

**Comment by jaruba** [comment]
```VLC 2.1.5 Ricewind``` seems to be behaving like WebChimera. It shows 00:00 as total duration and if I jump to the end of the stream it jumps just a few seconds,

**Comment by RSATom** [comment]
Maybe it's worth trying Vlc nightly build: http://nightlies.videolan.org/build/win32/last/ or current RC: http://nightlies.videolan.org/build/win32/vlc-2.2.0-20150106-0205/

**Comment by jaruba** [comment]
```VLC 3.0.0 - Nightly``` still has ".length" at 0 but seek works correctly. I'll check out the current RC too.

**Comment by jaruba** [comment]
```VLC 2.2.0 Weatherwax``` has all of the same issues as ```VLC 2.1.5 Ricewind```.

3.0.0 seems to get the correct position too (judging from the progress bar), I might even be able to calculate duration from it and ffprobe wouldn't be needed at all.

**Comment by RSATom** [comment]
It's very bad, since nobody know when Vlc 3.0 will be released - I doubt it will be this year...

but if you still want try WebChimera with it - it's pretty easy: you need place content of http://nightlies.videolan.org/build/win32/last/vlc-3.0.0-git-20150208-2058-win32.7z near the npWebChimera.dll

**Comment by jaruba** [comment]
After I moved the files I can use the demos on the site, but if I try to use it in node-webkit it says that it's missing "libgcc_s_sjlj-1.dll", but the file is in the ```%AppData%``` plugin's folder where it should be.

**Comment by RSATom** [comment]
with Node-Webkit, it will be even better if you will extract archive content near the `nw.exe` ( https://github.com/RSATom/WebChimera/issues/68 )

**Comment by jaruba** [comment]
Without the plugin files? Just the archive?

**Comment by RSATom** [comment]
do you uninstall plugin? if not - just copy libgcc_s_sjlj-1.dll to nw.exe folder, it will be enough.

**Comment by RSATom** [comment]
btw, I've registered chat on gitter: https://gitter.im/RSATom/WebChimera

**Comment by jaruba** [comment]
It worked, progress bar works as it should now with ".avi" files. Also, the math that calculates the total length is a lot more precise. This release of vlc will indeed fix both problems (just needs some tweaking in QML)

**Comment by RSATom** [comment]
Problem is we can't use it distribution, since it even not in alfa state...

**Comment by jaruba** [comment]
Yes, but others can use it in their node-webkit apps as a solution, if they run into this problem a lot and feel it's worth the risk. It's an optional fix to a very old bug. :)

(i joined the chatroom)

**Comment by RSATom** [comment]
Agree with you.

**Comment by RSATom** [comment]
@jaruba, can we close this issue?

**Comment by jaruba** [comment]
done

**Comment by RSATom** [comment]
Thanks!

**Comment by jaruba** [comment]
I may have an update on this, the problem is clearly with the avi encoding and partial avi files. Same avi files once fully downloaded have the correct total time length.

Further testing with ffprobe revealed that ffprobe itself only gets the correct total time length only when the file has been 100% downloaded.

When opening a avi stream from a partial file, VLC asks if you want to repair the file, otherwise it handles it with the same issues as seen in WebChimera.

In vlc options I found:

      --avi-index={0 (Ask for action), 1 (Always fix), 2 (Never fix), 3 (Fix when necessary)}
                                 Force index creation
          Recreate a index for the AVI file. Use this if your AVI file is
          damaged or incomplete (not seekable).

It doesn't state the default action, I'll have to do a few more tests, but it might be possible to make WebChimera's current libvlc.dll act like the nightly version by just activating this option for avi files.
