### ISSUE TITLE
ScrollView needed (Mac)

### ISSUE THREAD

**Issue by gyzerok** [RSATom/WebChimera#83]
Feature request for embeding [ScrollView](http://doc.qt.io/qt-5/qml-qtquick-controls-scrollview.html) into plugin.

**Comment by RSATom** [comment]
I'll check if it possible. Thanks!

**Comment by RSATom** [comment]
done for windows

**Comment by gyzerok** [comment]
Does it mean that this feature is not working for OS X at the moment or its just not tested?

**Comment by RSATom** [comment]
tbh it's not tested even on Windows :) but for mac OS X, `QtQuick.Controls` not tested and not added to `.dmg` (look how it was done for `Layouts` and `QtGraphicalEffects`: https://github.com/RSATom/WebChimera/blob/master/src/Mac/projectDef.cmake#L79)

**Comment by RSATom** [comment]
you could test Windows version if you wish: https://dl.dropboxusercontent.com/u/94817236/WebChimera_0.2.4.4_vlc_2.1.5.msi
