### ISSUE TITLE
QML string encoding

### ISSUE THREAD

**Issue by gyzerok** [RSATom/WebChimera#84]
For now QML supports only UTF8 encoding which cause some problems with adding subtitles functionality into player based on WebChimera.
So I'm requesting to add more encoding support into plugin.

**Comment by RSATom** [comment]
It's pretty easy, I think. So will add it to the next version.

**Comment by jaruba** [comment]
Are you sure about this @gyzerok ? Do you have a sample subtitle file?

From my attempts, I've never seen any kind of encoding limitation in QML, as long as the file is encoded properly, it will be read and display correctly.

**Comment by gyzerok** [comment]
@jaruba you've never see encoding limitations for sure? So what about [this](http://quabr.com/28273418/qml-javascript-convert-string-to-utf-8)? :D
Same problems here.

**Comment by jaruba** [comment]
Yeah, but that was a JavaScript limitation for me because the subtitles I was downloading wore not encoded properly.

I managed to fix that by talking to the webmaster of OpenSubtitles which was kind enough to enlighten me on a more obvious solution. Do you also have issues with OpenSubtitles or other subtitle websites?

**Comment by gyzerok** [comment]
In my case, I didn't have problems with encoding since I know one. But I cant predict an encoding of the file on the user side.

**Comment by jaruba** [comment]
Are you making a node-webkit app or are you requesting a subtitle upload on a website?

**Comment by jaruba** [comment]
In my experience, most subtitle files are ```iso-8859-1```, but in whatever way you request the subtitles, you should still be able to write them to a file and send the http or app link to qml, then fetch them with ```XMLHttpRequest```.

The [header](http://jsfiddle.net/9g6zkmof/2/) I received from OpenSubtitles did not include any encoding for me eighter.

The normal output of a OpenSubtitles file (with no encoding set in the header):
http://jsfiddle.net/9g6zkmof/1/

The output of the same subtitle link with forced ```iso-8859-1``` encoding:
http://jsfiddle.net/9g6zkmof/2/

**Comment by gyzerok** [comment]
Thank you for samples. I'll check.

You are a little bit wrong since OpenSubtitles comes with windows-1251 encoding. So you can easily convert them easily using [iconv](https://github.com/ashtuchkin/iconv-lite) javascript port.

There two popular native libraries with encoding prediction: iconv and icu. There is no way to use them into browser environment and a bad idea to use in nw.js. But @RSATom can add them into plugin itself.

**Comment by jaruba** [comment]
Having a ```iconv()``` in the JS and QML API would be great and it would solve a lot of problems with encoding.

**Comment by gyzerok** [comment]
@jaruba thats why i'm requesting this feature :)

**Comment by jaruba** [comment]
You might be right about QtQML being limited to UTF-8 encoding, I tested this file:
http://jsfiddle.net/9g6zkmof/7/

Which is encoded with CP1250 (with correct header), and although it looks alright in the fiddle, it has question marks when used in the Text element in QML.

**Comment by jaruba** [comment]
+1 This issue just became pretty important to me.

**Comment by RSATom** [comment]
Is there any standard way to work with encodings with QML? I.e. should I add some custom function, or it will be enough just use proper Qt build?

**Comment by jaruba** [comment]
I'm a bit unsure, I just found this:
http://qt-project.org/doc/qt-4.8/QTextCodec.html

Will have to see if any of these functions help to detect the encoding of a string or encode the string to UTF-8

**Comment by RSATom** [comment]
1) it's Qt 4.8, but we use Qt 5.4 now
2) It's Qt core, not Qml (I meant even if it's available in Qt it could be not available in Qml)

**Comment by jaruba** [comment]
Sorry, checked google in a hurry, then no, I can't find any way to detect or convert string encodings in QML or JavaScript.

**Comment by jaruba** [comment]
Functions like:
http://php.net/manual/en/function.iconv-get-encoding.php
and
http://php.net/manual/en/function.iconv-set-encoding.php

should solve this.

**Comment by RSATom** [comment]
ok, understand. How urgent it is?

**Comment by jaruba** [comment]
It's important, I can't say an urgency as I'm not on a deadline with anything. :)

**Comment by RSATom** [comment]
Understand, I'll try to take deal with this problem tomorrow.

**Comment by RSATom** [comment]
@jaruba witch datatype do you have in Qml to transcode to Utf8? Is it string or some sort of array?

**Comment by jaruba** [comment]
It's a string

**Comment by RSATom** [comment]
I've made some conversion support, but don't sure if it will work:
https://dl.dropboxusercontent.com/u/94817236/WebChimera_0.2.4.3_vlc_2.1.5.msi

I've added global functions `toUtf8(data, codec)`
about supported codecs you could read here: http://doc-snapshot.qt-project.org/qt5-5.4/qtextcodec.html#details

**Comment by jaruba** [comment]
but there's still no way to detect an encoding if it is unknown?

**Comment by RSATom** [comment]
no, encoding detection is complicated and not obvious task.

**Comment by jaruba** [comment]
I know I should of asked this a long time ago, but would it be possible to send a subtitle url (as url's support local files too with "file:///") from QML to libVlc to add it to the video? It already supports internal subtitles, and vlc itself seems to handle the problem with encoding flawlessly.

**Comment by RSATom** [comment]
Yes, it's possible.

**Comment by jaruba** [comment]
that would be amazing, as all the subtitle implementations we've done till now are just workarounds for not using vlc's internal features for this. :)

**Comment by RSATom** [comment]
funny :) ok, it will be easy.

**Comment by RSATom** [comment]
I think It could be closed, since don't think I will do encoding detection, and basic `toUtf8` was implemented already.
