### ISSUE TITLE
Youtube Videos are skipped

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#86]
If I add a youtube video, (eg: ```https://www.youtube.com/watch?v=s4GmNoXFojo``` ) to [this playlist](http://editor.webchimera.org/custom_titles), it will be skipped the first 2 times, 3rd time it works.

DebugView prints:

    [3100] access_http access error: cannot connect to r4---sn-gqn-vu2e.googlevideo.com:80
    [3100] access_mms access error: cannot connect to r4---sn-gqn-vu2e.googlevideo.com:80

**Comment by RSATom** [comment]
Any video or only some of them?

**Comment by jaruba** [comment]
All of them, the reason the demos work is that they all have only 1 youtube item in the playlist, and although it tries to skip it, it lands on the same item 3 times in a row until it finally plays it.

**Comment by RSATom** [comment]
and it always 3 times?

**Comment by jaruba** [comment]
From all current tests, yes. I'll have to do more tests to be sure though.

**Comment by RSATom** [comment]
then it really looks as bug. Thanks, I'll try to find the reason. Thanks!

**Comment by jaruba** [comment]
I can now confirm that it always works the 3rd time, but, it also seems it changes the link to the video from youtube.com to googlevideos.com when it works, so there's some kind of redirection going on.

The bigger issue here, one that is related to [this issue](http://ask.webchimera.org/237/customtitles-not-showing-for-youtube-videos) is that the player stores a lot of information about the video in ```.playlist.items[i].setting```, and by trying to reconnect to the youtube video, somewhere along the way, everything in ```.playlist.items[i].setting``` for that item is deleted.

This is the reason the custom titles didn't work and all settings (not just the titles) that I store there are lost until the video actually plays. In the meanwhile I've made a workaround only for the custom titles, I store them in an array that acts like a cache for the titles and isn't removed, but this should certainly be fixed.

**Comment by RSATom** [comment]
I think reason why '.setting' is resetting - youtube links work similar way as playlists since it needs redirections from original human readable youtube link to real video link (which are on `googlevideos.com`) and thus any settings reset since it's another playlist item already (old was deleted after redirection).
