### ISSUE TITLE
VLC Option run-time does not work for the m3u playlist in webchimera player

### ISSUE THREAD

**Issue by fapeci** [RSATom/WebChimera#87]
When adding an m3u playlist that includes option run-time (look below):

#EXTM3U
#EXTINF:0, Channel 1
#EXTVLCOPT:run-time=5
http://cdn-02.sdn.si/discoverychannel/discoverychannel.m3u8
#EXTINF:0, Channel 2
#EXTVLCOPT:run-time=5
rtsp://ewns-hls-b-stream.hexaglobe.net/rtpeuronewslive/it_vidan750_rtp.sdp

the webchimera player looses this information and it plays always the first item on the playlist and not the desired behaviour of switching between the items in the list after specific time as defined under run-time vlc option on m3u playlist

**Comment by RSATom** [comment]
Thank you for report!

**Comment by RSATom** [comment]
Partial workaround added in WebChimera Player: http://ask.webchimera.org/250/option-run-time-not-work-the-m3u-playlist-webchimera-player

In plugin it still should be fixed...

**Comment by fapeci** [comment]
The bug still exists as some MRL are not working as per the requirement see below discussion:
http://ask.webchimera.org/250/option-run-time-not-work-the-m3u-playlist-webchimera-player
@jaruba last comment is that:
Second mrl in the playlist works for me, it stops after 5 seconds (as it is the last element in the list), first one doesn't work because it never reaches the 5th second, as it does not start from 0. I'll try to make it a relative checkpoint.. (never imagined there are sources that don't start from 0)

**Comment by jaruba** [comment]
lol, it's funny to see yourself quoted. I've been thinking of all possible implications of the ```run-time``` parameter, you seem to have a lot of streams, there are also streams that have time set to 0 and never progresses, in this case I could only make a timeout, but that should pause when playback is paused, and I don't know if in this case it's possible to be used correctly in the player, I could only make it relative which would fix that particular case you used as an example, but cannot guarantee it will work for all your streams.

**Comment by jaruba** [comment]
Would fixing it just for streams that don't start from 0 help your project?

Or do you think you'll also have a need for streams that don't have progressive ```.time```? (as this would best be fixed in the plugin directly I think)

**Comment by fapeci** [comment]
Let's try your fix, maybe it would solve the problem permanently. I managed to build the plugin but need to go through it to find where should I intervene to include the functionality inside the plugin.

**Comment by jaruba** [comment]
@fapeci this is now fixed as mentioned in the comment here:

http://ask.webchimera.org/250/option-run-time-not-work-the-m3u-playlist-webchimera-player?show=286#a286

```run-time``` still won't work for streams that have no ```.time``` progression as mentioned above. Hope it is enough. :)

**Comment by RSATom** [comment]
@fapeci, is it solved for you? If yes, please close issue. Thanks in advance.

**Comment by RSATom** [comment]
I hope it's fixed...
