### ISSUE TITLE
External Subtitle Support

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#90]
It would be great to add external subtitle support in WebChimera Plugin directly.

The functionality I'm thinking about would be to be able to send an URL for a subtitle file to WebChimera from the API to add it to libVlc. This might be the simplest way of doing it as local files can also be added through an URL with ```file:///```.

**Comment by RSATom** [comment]
Thanks, scheduled to the next release.

**Comment by RSATom** [comment]
It seams this task little more complex than I thought. libvlc doesn't support load subtitles over network, only from local files. I can see two possible solutions:
1) download subtitle with QML/JS, pass it to plugin as string, save string to temp file, load file with libvlc;
2) pass url to plugin, download it internally by plugin to temp file, load file with libvlc

Question is: can you see any advantage in 1)?

**Comment by jaruba** [comment]
No, I don't see any advantage to 1.

**Comment by jaruba** [comment]
One question though, could it check if the http request returns a 200 response? Because if it doesn't, then there is an error and it should report it back somehow, maybe with an event? So an alternative URL can be used.

**Comment by jaruba** [comment]
And would external subtitles be subject to the same subtitle delay as the internal subtitles?

**Comment by RSATom** [comment]
> Because if it doesn't, then there is an error and it should report it back somehow, maybe with an event? 
I think I could notify QML/JS about subtitle loading problems.

> And would external subtitles be subject to the same subtitle delay as the internal subtitles?

I think yes, but didn't try.

**Comment by RSATom** [comment]
Implemented in QML API. Do you need same in JS API?

**Comment by jaruba** [comment]
nope, no need for it in JS API

**Comment by RSATom** [comment]
good, it will save some time to me.

**Comment by RSATom** [comment]
btw, if you wish you could try test build with external subtitles support:
https://dl.dropboxusercontent.com/u/94817236/WebChimera_0.2.4.4_vlc_2.1.5.msi

what was added:
* `vlcPlayer.subtitles.load(ulr)` function
* `vlcPlayer.subtitles.loadFinished` signal
* `vlcPlayer.subtitles.loadError` signal

**Comment by jaruba** [comment]
I'll try to test it today, thanks! :)

**Comment by jaruba** [comment]
It's actually ```vlcPlayer.subtitle.load(url)``` :)

**Comment by RSATom** [comment]
oops, fixed :)

**Comment by jaruba** [comment]
It's great that ``.subtitle.track = 0`` works to unload it too. But I don't think it should add them to ``.subtitle.count`` and ``.subtitle.description(i)``. There should be a function that just loads them, and another that adds them to the list, the one that adds it to the list, should also accept a custom "description".

Thing is, every time I add a new subtitle to the subtitle menu, I refresh the menu items, and if it's added to ``.subtitle`` too, I would get every loaded subtitle 2 times, one time from my array, a second time from ``.subtitle`` (as I show the interior subtitles too in the list)

**Comment by RSATom** [comment]
I'm afraid I can't change it - it's all inside libvlc.

**Comment by jaruba** [comment]
Is it possible to move the subtitles a bit more up? Or change the font size?

**Comment by RSATom** [comment]
Can't find anything related in libvlc api :(

All I found is

      --sub-margin=<integer [-2147483648 .. 2147483647]> 
                                 Force subtitle position
          You can use this option to place the subtitles under the movie,
          instead of over the movie. Try several positions.

in vlc startup options (`vlc -H`).

**Comment by jaruba** [comment]
Might be useful, can't be sure until testing it though.. Still, it isn't anything that bad, it's just about the cosmetics of it.

This is great though, is there a list of what subtitle extensions VLC supports? Should write them on the wiki..

**Comment by jaruba** [comment]
Also, how would I go about connecting to the signals, I would normally use:

    vlcPlayer.onMediaPlayerMediaChanged.connect( onVideoChanged );

does this mean it should work with:

    vlcPlayer.subtitle.onLoadError.connect( onSubtitleError );

**Comment by RSATom** [comment]
yea, exactly

about supported formats:

      --sub-type={auto,microdvd,subrip,subviewer,ssa1,ssa2-4,ass,vplayer,sami,dvdsubtitle,mpl2,aqt,pjs,mpsub,jacosub,psb,realtext,dks,subviewer1,vtt} 
                                 Subtitle format

**Comment by jaruba** [comment]
I'm currently testing it in powder, and sometimes I get this error in DebugView:

    [8244] main input error: no suitable demux module for `file/subtitle:///C:/Users/phant_000/AppData/Local/Temp/powder.Hp82441954439153.srt'
    [8244] main input error: VLC can't recognize the input's format
    [8244] main input error: The format of 'file:///C:/Users/phant_000/AppData/Local/Temp/powder.Hp82441954439153.srt' cannot be detected. Have a look at the log for details.


But if I select it again, it works.. ``.subtitle.loadError`` does not trigger.

**Comment by jaruba** [comment]
in ```C:\Users\phant_000\AppData\Local\Temp``` there is indeed a strange file called:

    powder.Hp82441954439153.srt1954439153.srt

**Comment by RSATom** [comment]
It's possible, since maybe problem happens after return from load call. I have no chance catch it.

paths are local, since I download it from internet by myself since libvlc supports only local subtitles.

**Comment by RSATom** [comment]
btw, did you get this error always on same .srt? or time to time? maybe it's a bug in file management after download.

**Comment by RSATom** [comment]
I delete this file right after pass it to libvlc, so maybe it's deleted before libvlc actually loads it.

**Comment by jaruba** [comment]
I just tested a few more videos, it seems to be only that specific file.. and only at the start of the app.. if i load it 10 times after, it always works.. Strange, I guess I'll have to test more in time, I can't be sure about this bug yet..

**Comment by RSATom** [comment]
is it possible this file just very big?

**Comment by RSATom** [comment]
I can add some delay before file delete to give libvlc more chances to load it.

**Comment by jaruba** [comment]
no, this error always happens on the very first subtitle loaded, if I close the app and open it again, I get the error again.

subtitle files are all very small..

**Comment by RSATom** [comment]
Maybe problem happen when media is not loaded yet? What if try load it on `mediaPlayerPlaying`?

**Comment by jaruba** [comment]
You know, I had a very similar issue with my implementation for external subtitles in QML. The first subtitle always gave a error and couldn't load so the alternative would be used, but the second time would work correctly. Could it be something in the node-webkit file caching?

Seeing that the file that can't be opened has "powder" in the name, I really think this can be related, but I don't imagine how or why.

**Comment by RSATom** [comment]
no, file name generated by plugin (it just takes name of current process as start), so don't think it could be related to Node-Webkit.

**Comment by jaruba** [comment]
is it possible to be related to the fact that the alternatives I'm using have the same file name?

for example:

    http://dl.opensubtitles.org/en/download/subencoding-utf8/1954453109.srt
    http://dl.opensubtitles.org/en/download/subencoding-cp1250/1954453109.srt
    http://dl.opensubtitles.org/en/download/file/1954453109.srt

are alternatives for the same file, only in different encodings, etc.

**Comment by RSATom** [comment]
> in C:\Users\phant_000\AppData\Local\Temp there is indeed a strange file called:
> powder.Hp82441954439153.srt1954439153.srt

I think I know what happens. It seams I forget reset file name after new file download.

**Comment by jaruba** [comment]
But how would that cause problems to only the first subtitle download?

**Comment by RSATom** [comment]
don't know, but file name definitely wrong

**Comment by RSATom** [comment]
but maybe it's not related...

**Comment by jaruba** [comment]
I checked this again with streaming (as there is a delay until it finds the subs)

So it found them at about minute 2, auto selected the language.

DebugView said:

    [8208] main input error: no suitable demux module for `file/subtitle:///C:/Users/phant_000/AppData/Local/Temp/powder.Hp82081954453109.srt'
    [8208] main input error: VLC can't recognize the input's format
    [8208] main input error: The format of 'file:///C:/Users/phant_000/AppData/Local/Temp/powder.Hp82081954453109.srt' cannot be detected. Have a look at the log for details.

File in temp folder is ``powder.Hp82081954453109.srt``, its the same file, but if I read it, it's a html page, this is because the subtitle server did not give a 200 response, it gave an http error response and printed a page.. So this is related somehow, because the issue in my implementation was also related to the subtitle server giving an error on the exact first file I call with the app.

**Comment by RSATom** [comment]
so problem is, plugin don't understand by some reason that it downloaded not subtitle file but error page... maybe it's bug on server?

**Comment by jaruba** [comment]
It's some sort of bug.. it seems on the server too.. I made it work correctly now, but the way I did it is so strange..

I made the app tell the plugin to download a dummy srt file with utf-8 forced encoding (a very small one) from opensubtitles right when the app is first opened.. now that dummy file gets the error and all of the other subtitles after it work.

I'll have to talk to the webmaster of OpenSubtitles more about this.

On the plugin side, I think it should realize that it gets a error page and not a subtitle and trigger ``vlcPlayer.subtitle.loadError``, because http response errors will be the most frequent with this function.

**Comment by RSATom** [comment]
>On the plugin side, I think it should realize that it gets a error page and not a subtitle and trigger vlcPlayer.subtitle.loadError, because http response errors will be the most frequent with this function.

Agree, just need find the way how to do it. Maybe I just forget check error somewhere...

**Comment by jaruba** [comment]
Or maybe I didn't hook to the signal correctly and don't catch the error? Could you try too?

You can try with any domain that does a not found page, as that is an 404 http error response.

**Comment by RSATom** [comment]
checked with:
```
Text {
    id: t;
    color: "white";
}

function success()
{
    t.text = "success";
}

function loadError()
{
    t.text = "error";
}

Component.onCompleted: {
    vlcPlayer.subtitle.load("http://www.webchimera.org/demos1/");
    vlcPlayer.subtitle.onLoadFinished.connect( success );
    vlcPlayer.subtitle.onLoadError.connect( loadError );
}
```

and got `error` - so it seems works.

**Comment by jaruba** [comment]
Try it with

    http://dl.opensubtitles.org/en/download/subencoding-utf8/file/1954586346.srt

As you can see it has a error, but it doesn't trigger the event. I used to avoid it in QML by verifying that the header had a 200 response code.

**Comment by jaruba** [comment]
It looks like this page returns a 200 response code anyway, I checked with this online tool:

http://tools.seobook.com/server-header-checker/?page=single&url=http%3A%2F%2Fdl.opensubtitles.org%2Fen%2Fdownload%2Fsubencoding-utf8%2Ffile%2F1954586346.srt&useragent=4&typeProtocol=10

But it was treated as an error in ```xmlhttprequest``` in QML.

**Comment by jaruba** [comment]
I think I remember now, I made another filter in QML that checked for "[CRITICAL ERROR]" in the response string, because these links also passed through my response code check, I don't think this is a issue with the plugin either.. It's also on the subtitle server side.

**Comment by RSATom** [comment]
Did you get any answer from webmaster of OpenSubtitles?

**Comment by jaruba** [comment]
Not yet..

**Comment by RSATom** [comment]
>1) download subtitle with QML/JS, pass it to plugin as string, save string to temp file, load file with libvlc;
So maybe we have to add this too to allow flexable handling of download errors?

**Comment by jaruba** [comment]
If it's easy to do, then it might be a good idea, otherwise I would still wait a bit, because it should be easy to add an error header on the server side

The thing that might make a function such as that worth making is that we already found a possible need for it, so it's not unreasonable to consider that there might be uses for it in the future as OpenSubtitles is not the only subtitle server with an API.

**Comment by RSATom** [comment]
> If it's easy to do, then it might be a good idea

It's easier than what was already implemented :)

**Comment by RSATom** [comment]
btw, do you know how big subtitles files could be?

**Comment by jaruba** [comment]
A typical movie has about 2 hours, Interstellar has 3 hours so that's way above the typical length and Interstellar's subtitle has 148kb, so I guess around 150kb max..

**Comment by RSATom** [comment]
so if I will set limit to subtitle maximum size, say 1Mb - it will be Ok?

**Comment by jaruba** [comment]
Should be.. I can't imagine any video that should need a subtitle file larger then 1Mb.

**Comment by RSATom** [comment]
Ok, will try implement it all this evening...

**Comment by RSATom** [comment]
@jaruba, what subtitle types are most popular from supported by libvlc: `microdvd,subrip,subviewer,ssa1,ssa2-4,ass,vplayer,sami,dvdsubtitle,mpl2,aqt,pjs,mpsub,jacosub,psb,realtext,dks,subviewer1,vtt`?
And which extensions they have?

**Comment by jaruba** [comment]
most popular is ".srt", second place is ".sub" in my opinion, but don't know what types they are.. I know "vtt" shares the ".srt" subtitle extension with another type though, from what I've read.

**Comment by RSATom** [comment]
I googled `.srt` = `subrip` and `.sub` = `subviewer1`
Is it ok if I add only these two at first time? Maybe some else?

**Comment by jaruba** [comment]
Sure, but why? aren't they handled by vlc anyway?

**Comment by RSATom** [comment]
It seems libvlc detect subtitle type by file extension. And I have to hardcode extensions for known subtitle types - you will have to specify type of subtitle by specifying value from enum on function call (it will be `.subtitle.loadFromString(string subtitle, enum type)`. I just don't know correct extensions for all subtitles types.

**Comment by jaruba** [comment]
Oh, only for load from string? Sure, sub and srt should be fine.

**Comment by RSATom** [comment]
anyway, it will be easy to add another types on next releases. I just will need to know correct extensions.

**Comment by jaruba** [comment]
Webmaster at OpenSubtitles responded and set error header codes for the pages that do not convert encoding correctly:

http://tools.seobook.com/server-header-checker/?page=single&url=http%3A%2F%2Fdl.opensubtitles.org%2Fen%2Fdownload%2Fsubencoding-utf8%2Ffile%2F1954586346.srt&useragent=1&typeProtocol=11

this now has a 501 error code instead of a 200 OK code. :)

Will have to send him a small node-webkit demo app to test with and understand the other problem (with the first download always showing an error). I expected this as it cannot be reproduced in the browser.

**Comment by RSATom** [comment]
Good, but please wait a little with sending him application. I've found serous bug in my subtitles loading implementation.

**Comment by jaruba** [comment]
Sure

**Comment by RSATom** [comment]
Btw, did you try load multiple subtitle files for same item? Are they all appears in subtitles list or only latest one?

**Comment by jaruba** [comment]
All are added to the subtitle list, even if they can't be loaded by VLC, it still adds them to the list.

**Comment by RSATom** [comment]
It's bad, then I have to limit maximum amount of extern subtitles to some value, since I have to keep all loaded subtitle files on disk until media not closed. And thus it's possible hacker attack by loading huge amount of fake subtitle files.

**Comment by jaruba** [comment]
Are you sure? Why would you need them on disk? I don't use the Tracks generated in the ``subtitle.count``, does VLC not allow you to delete the files after adding them to the list?

**Comment by RSATom** [comment]
No, it locks files after load, so I can't delete it even if want.

**Comment by jaruba** [comment]
So they can only be deleted on the ``media changed`` event or when plugin is unloaded? That is bad.. But it's highly possible that it only locks the selected subtitle file (as that one is being read right then), not all of the ones that it adds.

**Comment by RSATom** [comment]
> So they can only be deleted on the media changed event or when plugin is unloaded?

don't sure yet, I've met this at 1:00 am so have to go to sleep right after :)

> But it's highly possible that it only locks the selected subtitle file (as that one is being read right then), not all of the ones that it adds.

It's possible, didn't check it. But it will not help, I have to keep on disk all subtitles loaded to list, since they could be requested at any time

**Comment by jaruba** [comment]
Still, if that maximum number is 30-50 per video, it would only mean about 8 mb max, and that's more then enough, the subtitle servers themselves have a limitation for how many you can download per day..

**Comment by RSATom** [comment]
I was though about something about 10. But it's only per load of exact playlist item. If you will load them another time - counter will reset (since I will delete relatd files on item unload).

**Comment by RSATom** [comment]
Do you think 10 will be too low value?

**Comment by jaruba** [comment]
Would of at least set 20.. Just to make sure not many users actually get to feel this limitation, don't see 20 subtitles as a security risk..

**Comment by RSATom** [comment]
Ok, let's use 30 to be sure :)

**Comment by RSATom** [comment]
security risk will be to allow load hundreds, so 10 or 30 does not have any difference.

**Comment by RSATom** [comment]
Test version is ready: https://dl.dropboxusercontent.com/u/94817236/WebChimera_0.2.4.5_vlc_2.1.5.msi

Example how to use loading subtitles from string: `vlcPlayer.subtitle.loadFromString( "bla bla bla", VlcSubtitle.Subrip )`

**Comment by RSATom** [comment]
supported subtitles types:
        Microdvd = .sub
        Subrip = .srt
        Dks = .dks
        Vtt = .dks

Don't know what is last two formats, added them just because know their extensions.

**Comment by jaruba** [comment]
Don't think ".vtt" is a subtitle type. From what I know it's short for WebVTT that also uses ".srt", like Subrip.

**Comment by RSATom** [comment]
maybe, but this extension used and checked inside libvlc on subtitle file load:

````
/**
 * The possible extensions for subtitle files we support
 */
static const char sub_exts[][6] = {
    "idx", "sub",  "srt",
    "ssa", "ass",  "smi",
    "utf", "utf8", "utf-8",
    "rt",   "aqt", "txt",
    "usf", "jss",  "cdg",
    "psb", "mpsub","mpl2",
    "pjs", "dks", "stl",
    "vtt",""
};
````

**Comment by jaruba** [comment]
I downloaded the latest version and subtitles only worked a few times at the start then every thing I try to load a subtitle url I get this error in DebugView:

    [5268] main stream error: cannot pre fill buffer

**Comment by jaruba** [comment]
I now downgraded to WebChimera_0.2.4.4_vlc_2.1.5.msi and I get the same error with it too.

**Comment by jaruba** [comment]
Oh, I reached the subtitle download limit, that's why it can't load them anymore, I'll have to test this tomorrow

**Comment by RSATom** [comment]
How big is this limit?

**Comment by jaruba** [comment]
No idea, it isn't written anywhere, but I only reached it 2 times after doing extensive testing with subtitles almost all day and it resets fast enough..

**Comment by jaruba** [comment]
Version 0.2.4.5 seems to work fine, I can't find anything wrong with it atm..

**Comment by RSATom** [comment]
good, then I will release it today or tomorrow. btw, I will not release mac version this time, since there to many work to be done...

**Comment by jaruba** [comment]
Yeah, I expected that, that's why I made the mac version a frozen branch: https://github.com/jaruba/PowderPlayer/tree/mac

It has the old subtitle implementation and the bugs make it mostly unusable atm (btw, the bugs I posted seem to be the only ones affecting WebChimera Player, I tried to test most of the functionality). This one alone https://github.com/RSATom/WebChimera/issues/96 freezes the app every time it's closed or you try to go back to menu. :)

But it's a great start for mac, didn't even know if I'd manage making a mac version at first. :))

**Comment by RSATom** [comment]
then how about linux version? :)

**Comment by jaruba** [comment]
Do you think I should wait until the external subtitles are working in WebChimera Plugin on Mac too before releasing WebChimera Player with the changes to subtitles?

I'm asking this because the external subtitles will not work on the site and developer kit on mac if I make the changes to the repo until then.

**Comment by RSATom** [comment]
Is it possible make it dependent from plugin version? There are `.version` property available on JS side.

**Comment by jaruba** [comment]
I don't see why not..

**Comment by RSATom** [comment]
Then it will be better just enable/disable it by version checking.

**Comment by jaruba** [comment]
I've tested this a lot more to see the pros and cons between implementations.

Pros:
- subtitles look a lot more natural now
- a lot better subtitle parsing (handles html tags inside the subtitles perfectly, something that QML only did partially and there is no solution to this in QML from my research)
- subtitles show at given seconds a lot more accurately
- it supports all subtitle types

Cons:
- sometimes the subtitles are absurdly big (see this demo in fullscreen: http://www.webchimera.org/demos/external_subtitle , you must select the subtitle in the menu first, talking starts most at about minute 2)
- subtitles go under the toolbar (which can be annoying)

Now.. the subtitles being enormous seems to be related to the original video's width, if the video itself has a small width.. the subtitles will be very big, even in fullscreen, because libVLC doesn't know when the player was resized and for how much, so it always calculates subtitle size by original video's width.

I don't think ```--sub-margin``` will help to move the subtitles above the toolbar (although I may be wrong), because I'm pretty sure the margin will be calculated relative to the video feed position (and the video feed is positioned on the fly depending on player size and video size with ```fillMode: PreserveAspectFit```). I could of used this only if I could of changed it on the fly as I would always need to recalculate the position based on player resize.

The cons are pretty bad.. and the simptoms appear in a lot of video sources.. I'm wondering what to do in this case, as the old subtitle implementation was a lot more limited, it did not have these pretty big visual problems and looked a bit more professional, but the new subtitle implementation is a lot more powerful, but then what does it matter when you can't see the subtitles because of the toolbar or their so big that they go over a 3rd of the video in fullscreen..

**Comment by jaruba** [comment]
If only libVLC could calculate subtitle size and use ```--sub-margin``` based on the player current width, not the video's original width.. then everything would of worked perfectly.. :(

Now I'm thinking if I shouldn't revert to the old subtitle implementation because of these pretty serious issues with the new one..

**Comment by RSATom** [comment]
So, the only possible solution is somehow fix libvlc for better compatibility with libs like QmlVlc... It could take some time, and unfortunately I even don't know when I could start work on it.

Btw, about subtitles under toolbar - you could use two solutions:
1) Semitransparent toolbar;
2) Automatically reduce video height on toolbar show;

**Comment by jaruba** [comment]
Don't think those are good solutions.. The toolbar is already semi-transparent, I tested different transparency options when I made it like that, more then the current transparency isn't really ok.. as it needs to be visible too..

Seconds solution makes me feel like I'm trading one visual error for another visual error.. Think I'll revert to the old subtitle implementation ftm and think about this a bit more..

**Comment by RSATom** [comment]
Can't advise you anything in this case, sorry. So do as you think will be better. I never used subtitles, so even can't judge what is better.
