### ISSUE TITLE
VLC has updated

### ISSUE THREAD

**Issue by gyzerok** [RSATom/WebChimera#91]
Since VLC has updated i'm requesting to update dependencies in WebChimera in the upcoming release.

**Comment by RSATom** [comment]
What dependencies are you talking about?

**Comment by gyzerok** [comment]
I mean libraries such as libvlc, libvlccore. Another words all the libraries both VLC and WebChimera use.

**Comment by RSATom** [comment]
don't think it's good idea at least until vlc 2.2.1 will out

**Comment by gyzerok** [comment]
@RSATom Why do you think so?

**Comment by RSATom** [comment]
The problem is almost any Open Source project get really wide tested only after public release. i.e. not so many people use nightly builds as public releases. So we could consider first public release of almost any Open Source projects just as public beta...

**Comment by RSATom** [comment]
btw, why you want update it?  Do you plan to use WebCimera installer? I thought you need it only for Node-Webkit embedding?

**Comment by gyzerok** [comment]
Since 2.2.0 version VLC fixed problem with incorrect EOF detection. Some videos don't have received EOF as soon as playback started.
Yes, i'm gonna embed WC into nwjs app.

**Comment by RSATom** [comment]
If you don't use installer anyway - you could replace libvlc with required version without any problem. Then why you need installer with updated libvlc? Sorry, I don't understand.

**Comment by RSATom** [comment]
in v0.2.8 libvlc was updated to v2.2.1

**Comment by jaruba** [comment]
Great, VLC v2.2.1 partially fixes: https://github.com/RSATom/WebChimera/issues/80
