### ISSUE TITLE
Right Click and Double Click (Mac)

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#92]
On Mac if I right click when not in fullscreen (it works in fullscreen though), the context menu doesn't appear, as if the event wasn't triggered.

And double click doesn't work. Tested with the demos on the site.

**Comment by RSATom** [comment]
Did you test it on browser or Node-Webkit?

**Comment by jaruba** [comment]
I've tested in Safari, Firefox and Node-webkit. All show the same almost the same simptoms.

The only one that acts a bit differently is FireFox that actually treats the Right Click as a Left Click when not in Fullscreen. (right click also works in fullscreen here too)

Double Click doesn't work on any of them.

**Comment by RSATom** [comment]
Then I definitely missed or messed something. I'll check, thanks!
