### ISSUE TITLE
Using ".stop()" in the JS API crashes the browser/app (Mac)

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera#96]
As described in the title. (tested with Firefox and node-webkit)

**Comment by RSATom** [comment]
Thanks for report!

**Comment by RSATom** [comment]
Didn't catch it. On what page did you test it?

**Comment by jaruba** [comment]
https://github.com/jaruba/PowderPlayer/tree/mac - try downloading it and running powder.app, when you try to go back to main menu or close the window, it will freeze, I put a lot of ``console.log()`` after every line to realise that ``.stop()`` breaks the code and freezes the app. I tried using ``wjs("#webchimera").stop()`` in the browser too, and it froze the browser too and gave an error. (FireFox)

**Comment by RSATom** [comment]
what page did you open in firefox?

**Comment by jaruba** [comment]
http://www.webchimera.org/demos/default_skin - I think. can't be sure now though..

**Comment by RSATom** [comment]
ok, thanks, I'll try it there

**Comment by RSATom** [comment]
Firefox is just simplest way to debug plugins...

**Comment by jaruba** [comment]
I can't be sure of what version of FireFox I was using though.. But in case it doesn't crash when you test it, I could ask.

**Comment by RSATom** [comment]
I thought a little, maybe I don't get this error because I'm already changed something in plugin sources (which fix problem) before test. I'll try check with 0.2.4 to be sure.

**Comment by jaruba** [comment]
possibly, or maybe it's OS version specific?

**Comment by RSATom** [comment]
Don't think so. It should be something trivial.

**Comment by RSATom** [comment]
Btw, it could be specific to video source.

**Comment by jaruba** [comment]
Nope, I tested with a lot of them, many of them different in video type.. all showed the same simptoms, ``.stop()`` froze the browser/app completely, the next line after it never gets fired. From the tests it looked like the plugin went in an unending loop and the browser kept waiting for the function to return something and it never did.

**Comment by RSATom** [comment]
Did you get this problem with local files?

**Comment by jaruba** [comment]
local and remote files too

**Comment by jaruba** [comment]
If you tested with the v0.2.4 and it worked for you, I could try to get my hands on the same Mac, try the latest version to see if it works.. if it still has the same issues, I could install TeamViewer so you can see this error too?

**Comment by RSATom** [comment]
No, I didn't test it with v.0.2.4 only with current development version. Will try test with 0.2.4 at evening.

**Comment by RSATom** [comment]
btw, when exactly you get problem? when you click on toolbar stop button?

**Comment by RSATom** [comment]
And another question - how can I access plugin instance from JS console? `wjs('#webchimera')`?

**Comment by jaruba** [comment]
for all the demos on the site and powder too, which both have the id "webchimera" for the plugin object, yes.. ```wjs("#webchimera")``` gives access to the [player api](http://wiki.webchimera.org/Player_JavaScript_API), if you want to use the plugin api with ```wjs```, then use ```wjs("#webchimera").plugin```.

So to use ```.stop()``` from plugin api directly with wjs, just do ```wjs("#webchimera").plugin.stop()```

**Comment by RSATom** [comment]
understand, thanks.

**Comment by RSATom** [comment]
test version available:  https://dl.dropboxusercontent.com/u/94817236/WebChimera_%E2%80%9C0.2.5.1%E2%80%9D_vlc_2.2.0.dmg

Other latest Mac related fixes are there too.

**Comment by jaruba** [comment]
Will try to get my hands on a Mac in the next few days to test it.

**Comment by jaruba** [comment]
Took a while, I tested with the latest plugin version.

![mac-5](https://cloud.githubusercontent.com/assets/1777923/8147292/33a86c02-126c-11e5-9915-7f0502b6be99.png)

As can be seen in the image, everything in JS stops working after I call stop in the player. You can test this in the version of powder I sent you, this issue stops the app from closing and doesn't allow going back to the main menu. (as both these actions need the player to be stopped)

**Comment by jaruba** [comment]
The strange part is that it acts the same way (ie: freezes the browser window) as if it would be waiting for some sort of response from ``.stop()`` and it never gets anything. I'm wondering if just adding a response to ``.stop()`` such as ``true`` would solve this.

**Comment by RSATom** [comment]
I hope it fixed, but help with testing required: https://dl.dropboxusercontent.com/u/94817236/WebChimera_0.2.8.1_vlc_2.2.1.dmg
