### ISSUE TITLE
Question: Which video render(in windowless mode) you use in this plugin.

### ISSUE THREAD

**Issue by xinjiguaike** [RSATom/WebChimera#99]
Hi RSATom,

Sorry for the trouble, I have not research this project deeply for my emergency requirement from my job. So I want to ask you directly. I wanna know which video render(VMR7, VMR9, EVR or other) you use in the plugin and which window you render the video to. 

Looking forward to your reply!

Thanks,
Rudy

**Comment by RSATom** [comment]
None of them. It's using OpenGL shaders directly. Plugin don't use DirectShow, all decoding do via libvlc.

**Comment by RSATom** [comment]
miss you was asking about windowless mode - there I'm using `SetDIBitsToDevice` or `StretchDIBits` (depends of enabled `native-scaling` startup option): https://github.com/RSATom/WebChimera/blob/master/src/Win/FBVLC_Win.cpp#L110
But this is true only for `FBVLC compatibility mode`, in native mode (with using QML) plugin is always windowed (except on Mac OS X, where plugins are always windowless).

**Comment by xinjiguaike** [comment]
Hi RSATom, 
As you mentioned above, you used OpenGL shaders to render the video. But I need to use DShow to 
render the video(Like EVR), my problem is that the web element on the page was covered up by the video. I googled this problem , the saying is the window mode caused that, the plugin should use the windowless mode, but I don't know how to render the video in windowless mode with the EVR, use HDC? I need your help!!!

**Comment by RSATom** [comment]
If you need `windowless` mode - you could use FBVLC compatibility mode (FBVLC is previous generation of WebChimera plugin) :  https://github.com/RSATom/WebChimera/wiki/HTML-page-embedding#fbvlc-mode

But keep in mind, using `windowless` mode exclude possibility use any hardware accelerated renderer (DirectX, OpenGL, DirectShow etc.) - so you will get very poor performance anyway.

**Comment by RSATom** [comment]
Btw, what exactly elements do you want place over video? Maybe it will be better use QML?

**Comment by RSATom** [comment]
For `FBVLC` mode demo you could look: http://rsatom.github.io/fbvlc/ `windowless` mode presented there too.

**Comment by xinjiguaike** [comment]
Hi RSATom,

My project was based on DShow framework, I'm not sure the 'FBVLC compatibility mode' you mentioned was could be used in DShow.

In my project, I use EVR to render the video,  so I need a window handle to render the video on; In windowless mode, I can get the HDC(the drawable area) and the browser window handle. When I set the 'video window' to be the 'browser window', the web element(like a button) on it was still not visible.
Could you give me a solution about that?

**Comment by RSATom** [comment]
I'm absolutely not understand why you trying to use `WebChimera`. If I understand correctly you don't use browser, but `WebChimera` is browser plugin. So In your case you have to use libvlc directly and implement your own renderer.
